####################
## Home Assistant ##
####################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  # whitelist_external_dirs: #TODO
  #   - /config/

zone: !secret zones

# Web
cloud:
  google_actions: !include google_actions.yaml

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5
  server_port: 8448
  base_url: !secret base_url
  trusted_proxies:
    - 127.0.0.1
  use_x_forwarded_for: true

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_api_key
  zone: !secret cloudflare_zone
  records: !secret cloudflare_records

# Core
logger:
  default: warn

recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  purge_interval: 1

logbook:
  exclude:
    domains:
      - group
      - media_player
      - automation
    entities:
      - light.downstairs
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed

lovelace:
  mode: yaml

person:
  - name: Adam
    id: adam
    device_trackers:
      - device_tracker.dullage_s_iphone
  - name: Leanne
    id: leanne
    device_trackers:
      - device_tracker.iphone

config:
frontend:
history:
map:
mobile_app:
sun:
system_health:
updater:
shopping_list:

discovery:
  ignore:
    - igd

# Include
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
scene: !include_dir_merge_list scenes/
group: !include groups.yaml
shell_command: !include_dir_merge_named shell_commands/
sensor: !include_dir_merge_list sensors/
input_boolean: !include inputs/input_boolean.yaml
input_number: !include inputs/input_number.yaml
input_select: !include inputs/input_select.yaml
input_text: !include inputs/input_text.yaml

####################
##  Integrations  ##
####################

# Xiaomi Gateway
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway_key

# iOS
ios:
  push:
    categories:
      - name: Weekend Heating Warning
        identifier: "weekend_heating_warning"
        actions:
          - identifier: "HEATING_TURN_OFF"
            title: "Turn Heating Off"
            activationMode: "background"
            authenticationRequired: no
            destructive: no
            # behavior: 'textInput'
            # textInputButtonTitle: 'Silencio!'
            # textInputPlaceholder: 'Placeholder'
      - name: Overtime Log
        identifier: "overtime_log"
        actions:
          - identifier: "LOG_ONE_HOUR"
            title: "Log 1hr Overtime"
            activationMode: "background"
            authenticationRequired: no
            destructive: no
      - name: Clear Shopping List
        identifier: "clear_shopping_list"
        actions:
          - identifier: "CLEAR_SHOPPING_LIST"
            title: "Clear Shopping List"
            activationMode: "background"
            authenticationRequired: no
            destructive: yes
      - name: Disable Alarm
        identifier: "disable_alarm"
        actions:
          - identifier: "DISABLE_ALARM"
            title: "Disable Alarm (6hr)"
            activationMode: "background"
            authenticationRequired: no
            destructive: yes

# HomeKit
homekit:
  filter:
    include_entities:
      - light.downstairs
      - light.bathroom_lights
      - light.bathroom_mirror_lights
      - light.landing_light
      - light.master_bedroom_main
  entity_config:
    light.master_bedroom_main:
      name: "Bedroom Lights"

# Camera
camera:
  - platform: generic
    name: "HADashboard Image"
    still_image_url: !secret ha_dashboard_image

# Blink
blink:
  username: !secret blinkUsername
  password: !secret blinkPassword

# Text to Speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: "eu-west-1"
    text_type: ssml
    voice: Amy

# Media Player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# Notification Platforms
notify:
  # - platform: ios #TODO
  - name: email_adam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_username
    encryption: starttls
    username: !secret email_username
    password: !secret email_password
    recipient:
      - !secret email_address_adam
    sender_name: Home Assistant

# MQTT
mqtt:
  broker: 127.0.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Pilight
pilight:
  host: 192.168.0.15
  port: 5000

# IFTTT
ifttt:
  key: !secret ifttt_key

# Speedtest
speedtestdotnet:
  server_id: 7028
