- platform: mqtt
  name: Stairs
  state_topic: "light/stairs/state"
  command_topic: "light/stairs"
  rgb_state_topic: "light/stairs/rgb/state"
  rgb_command_topic: "light/stairs/rgb"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Landing Light
  state_topic: "light/landing/state"
  command_topic: "light/landing"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Bathroom Lights
  state_topic: "light/bathroom/state"
  command_topic: "light/bathroom"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Bathroom Mirror Lights
  state_topic: "light/bathroom_mirror/state"
  command_topic: "light/bathroom_mirror"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Main Kitchen Lights
  state_topic: "light/kitchen/state"
  command_topic: "light/kitchen"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Kitchen Left
  state_topic: "light/kitchen_left/state"
  command_topic: "light/kitchen_left"
  rgb_state_topic: "light/kitchen_left/rgb/state"
  rgb_command_topic: "light/kitchen_left/rgb"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Kitchen Right
  state_topic: "light/kitchen_right/state"
  command_topic: "light/kitchen_right"
  rgb_state_topic: "light/kitchen_right/rgb/state"
  rgb_command_topic: "light/kitchen_right/rgb"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Dining Room Lamp
  state_topic: "light/dining_room_lamp/state"
  command_topic: "light/dining_room_lamp"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Front Room Lamp
  state_topic: "light/front_room_lamp/state"
  command_topic: "light/front_room_lamp"
  payload_off: "0"
  payload_on: "1"
  retain: false
- platform: mqtt
  name: Master Bedroom Main
  command_topic: "light/master_bedroom_main"
  state_topic: "light/master_bedroom_main/state"
  payload_on: "1"
  payload_off: "0"
  retain: false
- platform: template
  lights:
    downstairs:
      value_template: "{{ is_state('group.downstairsExcStairs', 'on') }}"
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.downstairs_general
      turn_off:
        service: scene.turn_on
        data:
          entity_id: scene.downstairs_off
- platform: mqtt
  name: Garden Lights
  command_topic: "shellies/shelly1-32CDCA/relay/0/command"
  state_topic: "shellies/shelly1-32CDCA/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false