# - platform: pilight
  # switches: !include switches/pilight.yaml
- platform: broadlink
  host: 192.168.0.31
  mac: '34:ea:34:88:dd:1d'
  type: rm_mini
  switches: !include switches/broadlink.yaml
- platform: mqtt
  name: Ambilight Power
  command_topic: "switch/ambilight_power_supply"
  state_topic: "switch/ambilight_power_supply/state"
  #availability_topic: "switch/ambilight_power_supply/availability"
  payload_available: "1"
  payload_not_available: "0"
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Clothes Dryer
  command_topic: "switch/dryer"
  state_topic: "switch/dryer/state"
  #availability_topic: "switch/dryer/availability"
  payload_available: "1"
  payload_not_available: "0"
  payload_on: "1"
  payload_off: "0"