title: Home
views:
  - title: Main
    tab_icon: mdi:home-assistant
    cards: !include ui/main_tab.yaml
  - title: Climate
    tab_icon: mdi:thermostat
    cards: !include ui/climate_tab.yaml
  - title: AV
    tab_icon: mdi:remote
    cards: !include ui/av_tab.yaml
  - title: Miscellaneous
    tab_icon: mdi:hops
    cards: !include ui/miscellaneous_tab.yaml
  - title: Camera
    tab_icon: mdi:camera
    cards: !include ui/camera_tab.yaml
  - title: Admin
    tab_icon: mdi:account
    cards: !include ui/admin_tab.yaml