title: Home
views:
  - title: Main
    icon: mdi:home-assistant
    cards: !include config/ui/main_tab.yaml
    badges:
      - person.adam
      - person.leanne
  - title: AV
    icon: mdi:remote
    cards: !include config/ui/av_tab.yaml
  - title: Climate
    icon: mdi:thermostat
    cards: !include config/ui/climate_tab.yaml
  - title: Energy
    icon: mdi:home-lightning-bolt
    cards: !include config/ui/energy.yaml
    badges:
      - person.adam
      - person.leanne
  - title: Security
    icon: mdi:cctv
    cards: !include config/ui/security_tab.yaml
    badges:
      - person.adam
      - person.leanne
  - title: Miscellaneous
    icon: mdi:hops
    cards: !include config/ui/miscellaneous_tab.yaml
    badges:
      - person.adam
      - person.leanne
