title: Home
views:
  - title: Main
    icon: mdi:home-assistant
    cards: !include config/ui/main_tab.yaml
    badges:
      - sensor.adam_badge
      - sensor.leanne_badge
  - title: AV
    icon: mdi:remote
    cards: !include config/ui/av_tab.yaml
  - title: Climate
    icon: mdi:thermostat
    cards: !include config/ui/climate_tab.yaml
  - title: Security
    icon: mdi:cctv
    cards: !include config/ui/security_tab.yaml
  - title: Miscellaneous
    icon: mdi:hops
    cards: !include config/ui/miscellaneous_tab.yaml
    badges:
      - sensor.adam_badge
      - sensor.leanne_badge
