# Blast the sprinklers for a second to scare the birds away
bird_blaster:
  alias: Bird Blaster
  sequence:
    # - service: camera.record
    #   target:
    #     entity_id: camera.garden_hd
    #   data:
    #     filename: "/config/bird_blaster_recordings/{{ now().strftime('%Y-%m-%d %H-%M-%S') }}.mp4"
    #     duration: 8
    # - delay:
    #     seconds: 6
    - service: switch.turn_on
      entity_id: switch.sprinklers
    - delay:
        seconds: 1
    - service: switch.turn_off
      entity_id: switch.sprinklers
