# Blast the sprinklers for a second to scare the birds away
bird_blaster:
  alias: Bird Blaster
  sequence:
    - service: switch.turn_on
      entity_id: switch.sprinklers
    - delay:
        seconds: 1
    - service: switch.turn_off
      entity_id: switch.sprinklers
