# Volume
volume_up:
  alias: Volume Up
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBIAAABI5UQFRA5EBUPOhA5EDoQOREUEDkQFQ86EBUPFREUDxYPOhAVDzoQFBE5ETgRFBAUERQROBAVEDkQFRAVETgROBA6EAANBQ==

volume_upx4:
  alias: Volume Up
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBIAAABI5UQFRA5EBUPOhA5EDoQOREUEDkQFQ86EBUPFREUDxYPOhAVDzoQFBE5ETgRFBAUERQROBAVEDkQFRAVETgROBA6EAANBQ==
          - JgBIAAABI5UQFRA5EBUPOhA5EDoQOREUEDkQFQ86EBUPFREUDxYPOhAVDzoQFBE5ETgRFBAUERQROBAVEDkQFRAVETgROBA6EAANBQ==
          - JgBIAAABI5UQFRA5EBUPOhA5EDoQOREUEDkQFQ86EBUPFREUDxYPOhAVDzoQFBE5ETgRFBAUERQROBAVEDkQFRAVETgROBA6EAANBQ==
          - JgBIAAABI5UQFRA5EBUPOhA5EDoQOREUEDkQFQ86EBUPFREUDxYPOhAVDzoQFBE5ETgRFBAUERQROBAVEDkQFRAVETgROBA6EAANBQ==

volume_down:
  alias: Volume Down
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBIAAABJJQQFRA5EBUROBE5DzoQORAVEDkQFRE4EBUQFQ8VEBUQORE5EDkQFQ86ETgQFRAVDxUQFRAVDzoQFRAUDzsPOhA5EQANBQ==

volume_downx4:
  alias: Volume Down
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBIAAABJJQQFRA5EBUROBE5DzoQORAVEDkQFRE4EBUQFQ8VEBUQORE5EDkQFQ86ETgQFRAVDxUQFRAVDzoQFRAUDzsPOhA5EQANBQ==
          - JgBIAAABJJQQFRA5EBUROBE5DzoQORAVEDkQFRE4EBUQFQ8VEBUQORE5EDkQFQ86ETgQFRAVDxUQFRAVDzoQFRAUDzsPOhA5EQANBQ==
          - JgBIAAABJJQQFRA5EBUROBE5DzoQORAVEDkQFRE4EBUQFQ8VEBUQORE5EDkQFQ86ETgQFRAVDxUQFRAVDzoQFRAUDzsPOhA5EQANBQ==
          - JgBIAAABJJQQFRA5EBUROBE5DzoQORAVEDkQFRE4EBUQFQ8VEBUQORE5EDkQFQ86ETgQFRAVDxUQFRAVDzoQFRAUDzsPOhA5EQANBQ==

mute:
  alias: Mute
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABJpISEhI4EhISOBI3EzcSNxISEzcSEhM3EhITEhMSEhITNxISExISNxM3EjcTEhISExITNhM3EhITEhMSEjcTNhM3EgAFGAABJkkTAA0FAAAAAAAAAAA=

# Power
tv:
  alias: TV
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBGAJCUEDkQOhA5ERQPFRAVEBQRFBA5ETkPOhEUDxURFBEUDxUQFRA5ERQQFQ8VEBUQFQ8VEDoQFBA6EDkQORE5DzoROBIADQUAAA==

amp:
  alias: Amp
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABI5UQFBA6DxURORA5EDkRORAUETkQFBE5DxURFBAVDxUQOhA5EDkQOhA5EDkRFBAVDxUQFRAVEBQQFRAVDzoQORE5EAAFGgABI0wQAA0FAAAAAAAAAAA=

freeview_box:
  alias: Freeview Box
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABKJMTEhM3EzYTEhM3ExITEhMSExITEhMSExITEhM2ExITExI3EzcSExITEjcTNxITEjcTEhMSEzYUNhM3ExITEhM2EwAFjwABJ0oSAA0FAAAAAAAAAAA=

# HMDI Switcher
input_xbox:
  alias: Xbox
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABLJQUEhMTExITEhMTExITExM2EzcTNxM3EzcTNhQ2FDYUEhMTEzYUNhQSExITExMSExMTNhQSExITNxM3EzcTNhQ2FAAFJQABK0oTAA0FAAAAAAAAAAA=
          - JgBQAAABLJQUEhMTExITEhMTExITExM2EzcTNxM3EzcTNhQ2FDYUEhMTEzYUNhQSExITExMSExMTNhQSExITNxM3EzcTNhQ2FAAFJQABK0oTAA0FAAAAAAAAAAA=
          - JgBQAAABLJQUEhMTExITEhMTExITExM2EzcTNxM3EzcTNhQ2FDYUEhMTEzYUNhQSExITExMSExMTNhQSExITNxM3EzcTNhQ2FAAFJQABK0oTAA0FAAAAAAAAAAA=

input_freeview:
  alias: Freeview Box
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABKpYRFBEUERURFBEUEhQRFBE5ETkRORE5EzcRORE5ETkTEhMSEzcSFBEUERUSExEUERUSOBMSETkRORE5ETkTNxE5EwAFJwABK0oRAA0FAAAAAAAAAAA=
          - JgBQAAABKpYRFBEUERURFBEUEhQRFBE5ETkRORE5EzcRORE5ETkTEhMSEzcSFBEUERUSExEUERUSOBMSETkRORE5ETkTNxE5EwAFJwABK0oRAA0FAAAAAAAAAAA=
          - JgBQAAABKpYRFBEUERURFBEUEhQRFBE5ETkRORE5EzcRORE5ETkTEhMSEzcSFBEUERUSExEUERUSOBMSETkRORE5ETkTNxE5EwAFJwABK0oRAA0FAAAAAAAAAAA=

input_chromecast:
  alias: Chromecast
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABKZcTEhIUERQRFBIUExMQFRE5EzYUNhI4EzcTNxM3EzcTEhEVERQRORMSERURFBEUEhQRORI4EhMRORE5EzcTNxI3EwAFJwABKEwRAA0FAAAAAAAAAAA=
          - JgBQAAABKZcTEhIUERQRFBIUExMQFRE5EzYUNhI4EzcTNxM3EzcTEhEVERQRORMSERURFBEUEhQRORI4EhMRORE5EzcTNxI3EwAFJwABKEwRAA0FAAAAAAAAAAA=
          - JgBQAAABKZcTEhIUERQRFBIUExMQFRE5EzYUNhI4EzcTNxM3EzcTEhEVERQRORMSERURFBEUEhQRORI4EhMRORE5EzcTNxI3EwAFJwABKEwRAA0FAAAAAAAAAAA=

input_apple_tv:
  alias: Apple TV
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABKZcRFBITExMSExIUEhMSExI4EzcTNxI4EjgSOBE5ETkSExE5ERQTNxEVERQSExIUEhMRFRM2ERUSNxI5ETkRORA5FAAFJwABKEwSAA0FAAAAAAAAAAA=
          - JgBQAAABKZcRFBITExMSExIUEhMSExI4EzcTNxI4EjgSOBE5ETkSExE5ERQTNxEVERQSExIUEhMRFRM2ERUSNxI5ETkRORA5FAAFJwABKEwSAA0FAAAAAAAAAAA=
          - JgBQAAABKZcRFBITExMSExIUEhMSExI4EzcTNxI4EjgSOBE5ETkSExE5ERQTNxEVERQSExIUEhMRFRM2ERUSNxI5ETkRORA5FAAFJwABKEwSAA0FAAAAAAAAAAA=

input_guest:
  alias: Guest HDMI
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABL5QUEhQSExIUEhMTExITExM2FDYUNhQ2FDYUNhQ2FDYUExMSExMTEhM3ExMTEhMTExITNxM3EzcTExM2FDYUNhQ2FAAFJQABLkoTAA0FAAAAAAAAAAA=
          - JgBQAAABL5QUEhQSExIUEhMTExITExM2FDYUNhQ2FDYUNhQ2FDYUExMSExMTEhM3ExMTEhMTExITNxM3EzcTExM2FDYUNhQ2FAAFJQABLkoTAA0FAAAAAAAAAAA=
          - JgBQAAABL5QUEhQSExIUEhMTExITExM2FDYUNhQ2FDYUNhQ2FDYUExMSExMTEhM3ExMTEhMTExITNxM3EzcTExM2FDYUNhQ2FAAFJQABLkoTAA0FAAAAAAAAAAA=

# Amp Input
# amp_dvd:
#   alias: TV Audio
#   sequence:
#     - service: broadlink.send
#       data:
#         host: 192.168.0.215
#         packet:
#           - JgBQAAABJpQSEhI4EhISOBE4EjcSNxITEjcSExI3EhMTERITEhMSNxI3EhMSExISEhMSExI3EjcSExI3EjcSOBI3EjcSExITEgAFIwABJksSAA0FAAAAAAAAAAA=

# amp_cd:
#   alias: House Audio
#   sequence:
#     - service: broadlink.send
#       data:
#         host: 192.168.0.215
#         packet:
#           - JgBQAAABJpQSEhI4EhISOBI3EjcSOBETEjcSExI3EhMSExISEhMSNxI4EhISOBETEjcSExITEhISExI3EhMSNxITEjcSNxI4EgAFIwABJ0oSAA0FAAAAAAAAAAA=

# Channel Numbers
channel_0:
  alias: Channel 0
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBQAAABJpQRFBE5ETgRFBE5EBUQFRAVEBUQFRAVEBUQFRA5ERQRFBE4ERQRFBE5ERQQFRA5ETkROBE5EBUQORE5EDkRFBEUEQAFjQABJUsRAA0FAAAAAAAAAAA=

channel_2:
  alias: Channel 2
  sequence:
    - service: broadlink.send
      data:
        host: 192.168.0.215
        packet:
          - JgBIAAABKZIUERM2FDYTEhM2FBEUERQRFBEUERMSFBEUERQ2ExITEhMSEzYUNhMSEzYUNhMSEzcSEhQRFDYTNhQRFDYTNhQSEwANBQ==

# Scripts
all_av:
  alias: TV, Freeview & Amp
  sequence:
    - service: script.tv
    - service: script.amp
    - service: script.freeview_box
    - service: script.input_freeview

cbeebies:
  alias: CBeebies
  sequence:
    - service: script.channel_2
    - delay:
        seconds: 0.5
    - service: script.channel_0
    - delay:
        seconds: 0.5
    - service: script.channel_2
