# Based on the RGB values of one of the downstairs lights, work out if the lights are at normal brightness and if so, set the dim scene, else set the downstairs general scene.
dim_toggler:
  sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state_attr('light.frontroom_under_tv', 'rgb_color', (255, 191, 96)) %}
            scene.front_room_dim
          {% else %}
            scene.downstairs_general
          {% endif %}
