fidelux_show_calibration_image:
  sequence:
    - service: media_player.play_media
      entity_id: media_player.front_room_tv
      data:
        media_content_id: "http://192.168.0.49:50018/static/calibration.png"
        media_content_type: image/png

fidelux_show_current_calibration:
  sequence:
    - service: media_player.play_media
      entity_id: media_player.front_room_tv
      data:
        media_content_id: "{{ 'http://192.168.0.49:50018/camera?draw=true&random_number=' + (range(0,65536) | random | string) }}"
        media_content_type: image/png

fidelux_calibrate:
  sequence:
    - service: rest_command.calibrate_fidelux
    - delay:
        seconds: 5
    - service: media_player.media_stop
      entity_id: media_player.front_room_tv
