# Actions to run when we go to bed
goodnight:
  sequence:
    - service: climate.set_temperature
      data:
        entity_id: climate.nest
        temperature: 9
    - service: input_boolean.turn_off
      entity_id: input_boolean.tv_power
    - service: scene.turn_on
      entity_id: scene.downstairs_off
    # Only set the armed_night mode if currently disarmed.
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.ha_alarm
