- type: picture-elements
  image: /local/remote.png
  elements:
    - type: image
      image: /local/remote/power.png
      tap_action:
        action: call-service
        service: script.all_av
      style:
        top: 16.66%
        left: 16.66%
        width: 80px
        height: 80px
    - type: image
      image: /local/remote/volume-plus.png
      tap_action:
        action: call-service
        service: script.volume_upx4
      style:
        top: 16.66%
        left: 83.33%
        width: 80px
        height: 80px
    - type: image
      image: /local/remote/volume-minus.png
      tap_action:
        action: call-service
        service: script.volume_downx4
      style:
        top: 50%
        left: 83.33%
        width: 80px
        height: 80px
    - type: image
      image: /local/remote/volume-off.png
      tap_action:
        action: call-service
        service: script.mute
      style:
        top: 83.33%
        left: 83.33%
        width: 80px
        height: 80px
    # - type: image
    #   image: /local/remote/arrow-left.png
    #   tap_action:
    #     action: call-service
    #     service: script.sky_back
    #   style:
    #     top: 16.66%
    #     left: 50%
    #     width: 80px
    #     height: 80px
    - type: image
      image: /local/remote/remote.png
      style:
        top: 80%
        left: 33.33%

- type: entities
  title: TV Inputs
  show_header_toggle: false
  entities:
    - entity: script.input_freeview
      icon: mdi:video-input-hdmi
    - entity: script.input_chromecast
      icon: mdi:video-input-hdmi
    - entity: script.input_xbox
      icon: mdi:video-input-hdmi
    - entity: script.input_apple_tv
      icon: mdi:video-input-hdmi
    - entity: script.input_guest
      icon: mdi:video-input-hdmi

- type: entities
  title: AV Power
  show_header_toggle: false
  entities:
    # - entity: script.all_av
    #   icon: mdi:power
    - entity: input_boolean.all_av
      icon: mdi:power
    - entity: script.tv
      icon: mdi:power
    - entity: script.amp
      icon: mdi:power
    - entity: script.freeview_box
      icon: mdi:power

- type: entities
  title: House Audio Volume
  show_header_toggle: false
  entities:
    - input_number.whole_house_volume
    - type: section
      label: Areas
    - input_number.downstairs_volume
    - input_number.front_room_volume
    - input_number.bathroom_volume

- type: media-control
  entity: media_player.spotify_adam
