- type: thermostat
  entity: climate.house

- type: entities
  title: Heating Controls
  show_header_toggle: false
  entities:
    - entity: script.heating_quick_actions_21
      name: Set to 21
      icon: mdi:temperature-celsius
    - entity: script.heating_quick_actions_boost
      name: Heating Boost (5 min)
      icon: mdi:fire

- type: glance
  title: Indoor Climate
  show_header_toggle: false
  entities:
    - entity: sensor.house_thermostat_temperature
      name: Downstairs
    - entity: sensor.0x00158d00018256fa_temperature
      name: Upstairs
    - entity: sensor.loft_temperature
      name: Loft

- type: glance
  title: Humidity
  show_header_toggle: false
  entities:
    - entity: sensor.house_thermostat_humidity
      name: Downstairs
    - entity: sensor.0x00158d00018256fa_humidity
      name: Upstairs
    - entity: sensor.loft_humidity
      name: Loft
      icon: mdi:water-percent

- type: entities
  title: Outdoor Climate
  show_header_toggle: false
  entities:
    - sensor.dark_sky_temperature
    - sensor.dark_sky_precip_probability

- type: entities
  title: One-Off Heating Timer
  show_header_toggle: false
  entities:
    - sensor.ad_hoc_heating_time
    - input_number.ad_hoc_heating_time_hour
    - input_number.ad_hoc_heating_time_minute
    - entity: automation.ad_hoc_heating_timer
      name: Activated
      icon: mdi:alarm-multiple
