- type: gauge
  name: Current Power Consuption
  entity: sensor.home_power
  unit: w
  max: 8000
  needle: false
  severity:
    green: 200
    yellow: 600
    red: 1000

- type: entities
  title: Current Usage
  show_header_toggle: false
  entities:
    - sensor.current_energy_cost_ph
    - sensor.current_energy_cost_pm

- type: energy-date-selection
- type: energy-usage-graph

- type: sensor
  name: Server Cupboard
  entity: sensor.server_cupboard_power_consumption
  icon: mdi:server
  graph: line
  detail: 2
