- type: entities
  title: Security
  show_header_toggle: false
  entities:
    - type: section
      label: Motion Sensors
    - entity: binary_sensor.porch_motion
      name: Porch Motion Sensor (Night)
    - entity: binary_sensor.dining_room_motion_sensor_occupancy
      name: Dining Room Motion Sensor
    - entity: binary_sensor.stairs_motion_sensor_occupancy
      name: Stairs Motion Sensor
    - entity: binary_sensor.kitchen_motion_sensor_occupancy
      name: Kitchen Motion Sensor
    - entity: binary_sensor.bathroom_motion_sensor_occupancy
      name: Bathroom Motion Sensor

    - type: section
      label: Door Sensors
    - entity: binary_sensor.front_door_contact
      name: Front Door
    - entity: binary_sensor.kitchen_door_contact
      name: Kitchen Door
    - entity: binary_sensor.patio_doors_contact
      name: Patio Doors

    - type: section
      label: Window Sensors
    - entity: binary_sensor.bedroom_window_contact
      name: Bedroom Window
      icon: mdi:window-open-variant

- type: entities
  title: Modes
  show_header_toggle: false
  entities:
    - entity: input_boolean.guest_mode
      icon: mdi:account-group
    - entity: input_boolean.away
      icon: mdi:airplane

- type: glance
  title: Internet Speeds
  entities:
    - entity: sensor.speedtest_download
      name: Download
    - entity: sensor.speedtest_upload
      name: Upload
    - entity: sensor.speedtest_ping
      name: Ping

- type: entities
  title: Automation Control
  show_header_toggle: false
  entities:
    # - entity: automation.location_lights_auto_off
    #   name: Auto Light Off (Leaving)
    - entity: automation.light_timeouts_landing
      name: Landing Light Timeout
    - entity: automation.light_timeouts_master_bedroom
      name: Bedroom Light Timeout
    # - entity: automation.alarm
    #   name: Alarm
    - entity: script.morning_routine
      icon: mdi:weather-sunset-up

- type: entities
  title: "Home Arrival Notifications"
  show_header_toggle: false
  entities:
    - entity: automation.home_arrival_notifications_adam_arriving
      name: Adam (Notify Leanne)
      icon: mdi:bell-outline
    - entity: automation.home_arrival_notifications_leanne_arriving
      name: Leanne (Notify Adam)
      icon: mdi:bell-outline

- type: entities
  title: "Clothes Dryer"
  show_header_toggle: false
  entities:
    - switch.clothes_dryer
    - input_number.dryer_timeout

- type: entities
  title: "Zigbee"
  show_header_toggle: false
  entities:
    - entity: switch.zigbee_pairing
      name: Enable Pairing
      icon: mdi:zigbee

- type: entities
  title: "Misc"
  show_header_toggle: false
  entities:
    - entity: sensor.starling_effective_balance
      name: "Stock Price"
    - script.render_voice_assistant_config
    - entity: switch.microwave
      name: Microwave
      icon: mdi:microwave
    - entity: group.pi_holes
      name: Pi-hole Ad-Blocking
      icon: mdi:pi-hole

- type: entities
  title: Effy Flea Treatment
  show_header_toggle: false
  entities:
    - entity: input_datetime.last_effy_flea
      name: Last Effy Flea
      icon: mdi:cat
