- type: alarm-panel
  entity: alarm_control_panel.ha_alarm
  name: Alarm
  states:
    - arm_away
    - arm_night

- type: entities
  title: Motion Sensors
  show_header_toggle: false
  entities:
    - entity: binary_sensor.porch_motion
      secondary_info: last-changed
      name: Porch Motion Sensor (Night)
    - entity: binary_sensor.dining_room_motion_sensor_occupancy
      secondary_info: last-changed
      name: Dining Room Motion Sensor
    - entity: binary_sensor.stairs_motion_sensor_occupancy
      secondary_info: last-changed
      name: Stairs Motion Sensor
    - entity: binary_sensor.kitchen_motion_sensor_occupancy
      secondary_info: last-changed
      name: Kitchen Motion Sensor
    - entity: binary_sensor.kitchen_motion_sensor_2_occupancy
      secondary_info: last-changed
      name: Kitchen Motion Sensor 2
    - entity: binary_sensor.bathroom_motion_sensor_occupancy
      secondary_info: last-changed
      name: Bathroom Motion Sensor

- type: entities
  title: Doors / Windows
  show_header_toggle: false
  entities:
    - type: section
      label: External Doors
    - entity: binary_sensor.front_door_contact
      secondary_info: last-changed
      name: Front Door
    - entity: binary_sensor.garden_door_contact
      secondary_info: last-changed
      name: Kitchen Door
    - entity: binary_sensor.patio_doors_contact
      secondary_info: last-changed
      name: Patio Doors

    - type: section
      label: Internal Doors
    - entity: binary_sensor.kitchen_door_sensor_contact
      secondary_info: last-changed
      name: Kitchen Door
    - entity: binary_sensor.front_room_door_sensor_contact
      secondary_info: last-changed
      name: Front Room Door
    - entity: binary_sensor.bathroom_door_sensor_contact
      secondary_info: last-changed
      name: Bathroom Door
    - entity: binary_sensor.master_bedroom_door_sensor_contact
      secondary_info: last-changed
      name: Master Bedroom Door
    - entity: binary_sensor.blues_room_door_sensor_contact
      secondary_info: last-changed
      name: Blue's Bedroom Door

    - type: section
      label: Windows
    - entity: binary_sensor.bedroom_window_contact
      secondary_info: last-changed
      name: Bedroom Window
      icon: mdi:window-open-variant

- type: picture-entity
  entity: camera.front_door

- type: picture-entity
  entity: camera.side

- type: picture-entity
  entity: camera.garden

- type: glance
  title: Rejected Detections (Per Hour)
  columns: 3
  entities:
    - entity: sensor.rejected_front_door_per_hr
      name: Front Door
      icon: mdi:account-off
    - entity: sensor.rejected_side_per_hr
      name: Side
      icon: mdi:account-off
    - entity: sensor.rejected_garden_per_hr
      name: Garden
      icon: mdi:account-off

- type: entities
  entities:
    - entity: sensor.cctv_queue_depth
      name: CCTV Queue
      icon: mdi:cctv

- type: entities
  title: Camera Stream
  show_header_toggle: false
  entities:
    - input_select.camera
    - input_select.media_player
    - entity: script.camera_stream
      name: Stream Camera
      icon: mdi:cast
