- platform: rest
  name: Fidelux
  resource: https://fidelux.dullage.com
  body_on: '{"state": true}'
  body_off: '{"state": false}'
  is_on_template: "{{ value_json.state }}"
  headers:
    Content-Type: application/json
