- platform: rest
  name: Fidelux
  resource: http://192.168.0.50:8000
  body_on: '{"state": true}'
  body_off: '{"state": false}'
  is_on_template: "{{ value_json.state }}"
  headers:
    Content-Type: application/json
