- platform: template
  switches:
    ambilight:
      value_template: "{{ is_state('binary_sensor.ambilight', 'on') }}"
      turn_on:
        service: rest_command.ambilight_on
      turn_off:
        service: rest_command.ambilight_off
