- name: Downstairs Off
  entities:
    group.downstairs_ex_stairs:
      state: "off"
    input_select.maestro_stairs: "Shutdown"
    switch.abilight:
      state: "off"

- name: Downstairs General
  entities:
    input_select.maestro_stairs: "Startup"
    group.kitchen_leds:
      state: "on"
    light.ambilight:
      state: "off"
    group.tv:
      state: "on"
      brightness: 200
      xy_color: [0.49, 0.41]
    light.front_room_lamp:
      state: "on"
    light.dining_room_lamp:
      state: "on"
    light.corner_lamp:
      state: "on"
      effect: "Fire 2012"

- name: Downstairs Dim
  entities:
    input_select.maestro_stairs: "Startup"
    group.kitchen_leds:
      state: "on"
    light.ambilight:
      state: "off"
    group.tv:
      state: "on"
      brightness: 100
      xy_color: [0.49, 0.41]
    light.front_room_lamp:
      state: "off"
    light.dining_room_lamp:
      state: "off"
    light.corner_lamp:
      state: "off"

- name: kitchen_leds_dim
  entities:
    light.kitchen_left_bottom:
      state: "on"
      effect: Rainbow
    light.kitchen_right_bottom:
      state: "on"
      effect: Rainbow
    light.kitchen_left_top:
      state: "on"
      effect: Rainbow
    light.kitchen_right_top:
      state: "on"
      effect: Rainbow

- name: kitchen_leds_bright
  entities:
    light.kitchen_left_bottom:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_right_bottom:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_left_top:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_right_top:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
