- name: Downstairs Off
  entities:
    group.downstairs_ex_stairs:
      state: "off"
    input_select.maestro_stairs: "Shutdown"

- name: Downstairs General
  entities:
    input_select.maestro_stairs: "Startup"
    group.kitchen_leds:
      state: "on"
    light.front_room_lamp:
      state: "on"
    light.dining_room_lamp:
      state: "on"
    light.corner_lamp:
      state: "on"
      effect: "Rainbow"
    group.tv:
      state: "on"
      brightness: 200
      xy_color: [0.49, 0.41]

- name: Downstairs Dim
  entities:
    light.front_room_lamp:
      state: "off"
    group.tv:
      state: "on"
      brightness: 85
      xy_color: [0.50, 0.42]
    light.dining_room_lamp:
      state: "off"
    light.corner_lamp:
      state: "on"
      effect: "Rainbow"

- name: kitchen_leds_dim
  entities:
    light.kitchen_left_bottom:
      state: "on"
      # rgb_color: [255,200,145]
      # brightness: 100
      effect: Rainbow
    light.kitchen_right_bottom:
      state: "on"
      # rgb_color: [255,200,145]
      # brightness: 100
      effect: Rainbow
    light.kitchen_left_top:
      state: "on"
      # rgb_color: [255,200,145]
      # brightness: 0
      effect: Rainbow
    light.kitchen_right_top:
      state: "on"
      # rgb_color: [255,200,145]
      # brightness: 0
      effect: Rainbow

- name: kitchen_leds_bright
  entities:
    light.kitchen_left_bottom:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_right_bottom:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_left_top:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
    light.kitchen_right_top:
      state: "on"
      rgb_color: [255,195,135]
      brightness: 255
      effect: None
