- name: Downstairs Off
  entities:
    group.downstairs_ex_stairs:
      state: "off"
    input_select.maestro_stairs: "Shutdown"

- name: Downstairs General
  entities:
    input_select.maestro_stairs: "Startup"
    # light.kitchen_left:
    #   state: "on"
    #   effect: "None"
    #   rgb_color: [255,200,145]
    #   brightness: 255
    # light.kitchen_right:
    #   state: "on"
    #   effect: "None"
    #   rgb_color: [255,200,145]
    #   brightness: 255
    light.front_room_lamp:
      state: "on"
    light.dining_room_lamp:
      state: "on"
    light.corner_lamp:
      state: "on"
      effect: "Rainbow"
      # brightness: 255
      # rgb_color: [255,181,108]
    group.tv:
      state: "on"
      brightness: 200
      xy_color: [0.49, 0.41]

- name: Downstairs Dim
  entities:
    light.front_room_lamp:
      state: "off"
    group.tv:
      state: "on"
      brightness: 85
      xy_color: [0.50, 0.42]
    light.dining_room_lamp:
      state: "off"
    light.corner_lamp:
      state: "on"
      effect: "Rainbow"
      # brightness: 100
      # rgb_color: [255,181,108]
