- alias: air_freshener
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.lodge_door_contact
    from: 'on'
    to: 'off'
  action:
    - service: script.air_freshener
    - delay:
        minutes: 15
