# Send occupants an iOS notification is a door or window is opened whilst the house is unoccupied.
- alias: alarm
  initial_state: true
  trigger:
    # Front Door
    - platform: state
      entity_id: binary_sensor.front_door_contact
      to: "on"
    # Garden Door
    - platform: state
      entity_id: binary_sensor.garden_door_contact
      to: "on"
    # Patio Doors
    - platform: state
      entity_id: binary_sensor.patio_doors_contact
      to: "on"
    # Master Bedroom Window
    - platform: state
      entity_id: binary_sensor.bedroom_window_contact
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
      - condition: template
        value_template: "{{ states('person.leanne') != 'home' }}"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Alarm: Door / Window Opened!"
        data:
          push:
            category: disable_alarm
    - service: notify.mobile_app_iphone
      data:
        message: "Alarm: Door / Window Opened!"
        data:
          push:
            category: disable_alarm

# Disable the alarm for 6 hours if "Disable" button pressed in the iOS notification.
- alias: alarm_disable
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: DISABLE_ALARM
  action:
    - service: automation.turn_off
      entity_id: automation.alarm
    - delay: "06:00"
    - service: automation.turn_on
      entity_id: automation.alarm

- alias: alarm_on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alarm
    to: "on"
  action:
    service: shell_command.start_cctv_uploader

- alias: alarm_off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alarm
    to: "off"
  action:
    service: shell_command.stop_cctv_uploader
