# Needs comment
- alias: all_av_input_boolean_on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.all_av
    to: "on"
  action:
    service: script.all_av

- alias: all_av_input_boolean_off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.all_av
    to: "off"
  action:
    service: script.all_av

- alias: all_av_input_boolean_update_on
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.tv_power_consumption
    above: 29
  action:
    - service: automation.turn_off
      entity_id: automation.all_av_input_boolean_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.all_av
    - service: automation.turn_on
      entity_id: automation.all_av_input_boolean_on

- alias: all_av_input_boolean_update_off
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.tv_power_consumption
    below: 30
  action:
    - service: automation.turn_off
      entity_id: automation.all_av_input_boolean_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.all_av
    - service: automation.turn_on
      entity_id: automation.all_av_input_boolean_off
