# Toggle the bathroom lights when the pull cord is pulled
- alias: bathroom_switch
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_switch
    to:
      - "on"
      - "off"
  action:
    service: light.toggle
    entity_id: light.bathroom_all
