# Arm the garden and entrance cameras when we've both left the house.
- alias: blink_cameras_arm_garden_on_exit
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
  condition:
    condition: template
    value_template: "{{ states('group.everyone') != 'home' }}"
  action:
    - service: camera.enable_motion_detection
      entity_id: camera.blink_garden
    - service: camera.enable_motion_detection
      entity_id: camera.entrance

# Disarm the garden and entrance cameras if either of us come home between 7am and 10pm.
- alias: blink_cameras_disarm_garden_on_daytime_arrival
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.adam
      to: home
    - platform: state
      entity_id: person.leanne
      to: home
  condition:
    condition: time
    after: "07:00:00"
    before: "22:00:00"
  action:
    - service: camera.disable_motion_detection
      entity_id: camera.blink_garden
    - service: camera.disable_motion_detection
      entity_id: camera.entrance

# Arm the garden camera at 10pm as long as both back doors are shut. If either are open we're probably having a late BBQ.
- alias: blink_cameras_arm_garden_at_night
  initial_state: true
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    condition: and
    conditions:
      # Back Door
      - condition: state
        entity_id: binary_sensor.garden_door_contact
        state: "off"
      # Patio Doors
      - condition: state
        entity_id: binary_sensor.patio_doors_contact
        state: "off"
  action:
    service: camera.enable_motion_detection
    entity_id: camera.blink_garden

# After 10pm, arm the garden camera once both back doors are shut (the BBQ is over).
- alias: blink_cameras_arm_garden_at_night_on_door_close
  initial_state: true
  trigger:
    # Back Door
    - platform: state
      entity_id: binary_sensor.garden_door_contact
      to: "off"
    # Patio Doors
    - platform: state
      entity_id: binary_sensor.patio_doors_contact
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "22:00:00"
      # Back Door
      - condition: state
        entity_id: binary_sensor.garden_door_contact
        state: "off"
      # Patio Doors
      - condition: state
        entity_id: binary_sensor.patio_doors_contact
        state: "off"
  action:
    service: camera.enable_motion_detection
    entity_id: camera.blink_garden

# Note: The entrance camera is armed when the Google "Goodnight" routine is run.

# As long as one of us is home, disarm the garden and entrance cameras at 6am.
- alias: blink_cameras_disarm_garden_in_morning
  initial_state: true
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    condition: template
    value_template: "{{ states('group.everyone') == 'home' }}"
  action:
    - service: camera.disable_motion_detection
      entity_id: camera.blink_garden
    - service: camera.disable_motion_detection
      entity_id: camera.entrance
