# Turn off all but one light when the Blues Night Light is turned on
- alias: blues_night_light_on
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.blues_night_light
    to: "on"
  action:
    - service: light.turn_off
      entity_id: light.blues_room_1
    - service: light.turn_off
      entity_id: light.blues_room_2
    - service: light.turn_on
      entity_id: light.blues_room_3
      data:
        brightness: 40
        kelvin: 2400
    - service: light.turn_off
      entity_id: light.blues_room_4
    - service: switch.turn_off
      entity_id: switch.rainbow_light

# Automatically turn off the Blues Night Light after 2 hours
- alias: blues_night_light_off
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.blues_night_light
    to: "on"
    for:
      minutes: 120
  action:
    - service: switch.turn_off
      entity_id: switch.blues_night_light
    - service: light.turn_off
      entity_id: light.blues_room_all

# Turn off Blue's nightlight if the main lights are turned on
- alias: blues_night_light_off_main_lights_on
  initial_state: true
  trigger:
    platform: state
    entity_id: light.blues_room_all
    to: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.blues_night_light
