# 
- alias: blues_night_light_on
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.blues_night_light
    to: "on"
  action:
    - service: light.turn_off
      entity_id: light.blues_room_1
    - service: light.turn_off
      entity_id: light.blues_room_2
    - service: light.turn_off
      entity_id: light.blues_room_3
    - service: light.turn_on
      entity_id: light.blues_room_4
      data:
        brightness: 40
        kelvin: 2400

# Automatically turn off the Blues Night Light after 60 minutes
- alias: blues_night_light_off
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.blues_night_light
    to: "on"
    for:
      minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.blues_night_light
    - service: light.turn_off
      entity_id: light.blues_room_all