- alias: cartoons_on_tv_off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.cartoons
    to: 'on'
  condition:
    condition: state
    entity_id: media_player.apple_tv
    state: "standby"
  action:
    - service: media_player.turn_on
      entity_id: media_player.apple_tv
    - delay:
        seconds: 15
    - service: script.cbeebies
    - service: input_boolean.turn_off
      entity_id: input_boolean.cartoons

- alias: cartoons_on_tv_on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.cartoons
    to: 'on'
  condition:
    condition: template
    value_template: "{{ not is_state('media_player.apple_tv', 'standby') }}"
  action:
    - service: script.cbeebies
    - service: input_boolean.turn_off
      entity_id: input_boolean.cartoons
