# Send a warning notification if the CCTV queue depth is too high
- alias: cctv_queue_depth_warning
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.cctv_queue_depth
    above: 20
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Warning: There are a lot of CCTV videos waiting to be processed."

- alias: cctv_queue_age_warning
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.cctv_queue_depth_old
    above: 0
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Warning: There are old CCTV videos waiting to be processed."

- alias: cctv_queue_age_warning_periodic
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "/3"
  condition:
    - condition: numeric_state
      entity_id: sensor.cctv_queue_depth_old
      above: 0
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Reminder: There are old CCTV videos waiting to be processed."

