# If there are more than 20 rejected CCTV clips from an individual camera in the last hour, send a notification.
# Ignore those during the day which are mainly caused by wind and only look at night where it's always spider webs!
- alias: cctv_high_rejections_warning
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.rejected_front_door_per_hr
      - sensor.rejected_side_per_hr
      - sensor.rejected_garden_per_hr
    above: 20
  condition:
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: |
          There have been a high number of rejected CCTV recordings:

          Front Door: {{ states('sensor.rejected_front_door_per_hr') }}
          Side: {{ states('sensor.rejected_side_per_hr') }}
          Garden: {{ states('sensor.rejected_garden_per_hr') }}
    - delay:
        hours: 6
