# # Update Cloudflare on startup, good for power cuts when a new IP is issued.
- alias: cloudflare_on_ha_start
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    # 30 second delay to allow service to become available
    - delay:
        seconds: 30
    - service: cloudflare.update_records
