# Turn the coat rack lights on when the entrance light is turned on
- alias: coat_rack_light_on
  initial_state: true
  trigger:
    platform: state
    entity_id: light.entrance_light
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.coat_rack

# Turn the coat rack lights off when the entrance light is turned off
- alias: coat_rack_light_off
  initial_state: true
  trigger:
    platform: state
    entity_id: light.entrance_light
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.coat_rack
