# Doorbell
- alias: doorbell
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.doorbell_action
      to: 
        - "single"
        - "double"
        - "triple"
        - "quadruple"
        - "release"
  action:
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.nest_minis
        message: "<speak>Humans. There is someone at the front door.</speak>"
    - service: camera.snapshot
      entity_id: camera.front_door
      data:
        filename: /media/front_door.jpg
    - service: notify.iphones
      data:
        message: "Doorbell"
        data:
          image: /media/local/front_door.jpg
          url: /lovelace/4  # CCTV Tab
    - delay:
        seconds: 5
