# Doorbell
- alias: doorbell
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.doorbell_action
      to: 
        - "single"
        - "double"
        - "triple"
        - "quadruple"
        - "release"
  action:
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.nest_minis
        message: "<speak>Humans. There is someone at the front door.</speak>"
    - service: notify.iphones
      data:
        message: "Doorbell"
        data:
          attachment:
            content-type: jpeg
          entity_id: camera.front_door
    - delay:
        seconds: 5
