# Doorbell
- alias: doorbell
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d000204a3c3_click
    from: ""
  condition:
    # 5s Debounce
    condition: template
    value_template: >
      {% set automation_name = "doorbell" %}
      {% set debounce_seconds = 5 %}
      {{ 
        (states.automation[automation_name].attributes.last_triggered == none) 
        or (as_timestamp(state_attr('automation.' + automation_name, 'last_triggered')) < (as_timestamp(now()) - debounce_seconds))
      }}
  action:
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.google_homes
        message: "<speak>Humans. There is someone at the front door.</speak>"
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Doorbell"
    - service: notify.mobile_app_iphone
      data:
        message: "Doorbell"
    - service: shell_command.blink
