# Turn off the master bedroom fan at 4am (when the blind shuts)
- alias: fan_auto_off
  initial_state: true
  trigger:
    platform: time
    at: "04:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.fan
