# Turn the fan off if the blind closes by more than 70%.
- alias: fan_auto_off_blind
  initial_state: true
  trigger:
    platform: state
    entity_id: cover.bedroom_blind
  condition:
    condition: template
    value_template: "{{ state_attr('cover.bedroom_blind', 'current_position') < 30 }}"
  action:
    service: switch.turn_off
    entity_id: switch.fan

# Turn the fan off if the bedroom window is closed.
- alias: fan_auto_off_window
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_window_contact
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.fan

# Turn the fan on if the blind is open and the bedroom window is open.
- alias: fan_auto_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: cover.bedroom_blind
    - platform: state
      entity_id: binary_sensor.bedroom_window_contact
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.bedroom_window_contact
        state: "on"
      - condition: template
        value_template: "{{ state_attr('cover.bedroom_blind', 'current_position') >= 30 }}"
  action:
    service: switch.turn_on
    entity_id: switch.fan
