- alias: fidelux_downstairs_general
  initial_state: true
  trigger:
    platform: state
    entity_id: scene.downstairs_general
  condition:
    condition: state
    entity_id: switch.fidelux
    state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.fidelux
    - delay:
        seconds: 3
    - service: scene.turn_on
      entity_id: scene.downstairs_general

- alias: fidelux_downstairs_timeout
  initial_state: true
  trigger:
    platform: state
    entity_id: scene.downstairs_timeout
  condition:
    condition: state
    entity_id: switch.fidelux
    state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.fidelux
    - delay:
        seconds: 3
    - service: scene.turn_on
      entity_id: scene.downstairs_timeout
