# Allow ios actions to dynamically call services using the format "api:{{ service }}/{{ entity id }}"
- alias: ios_action_api
  initial_state: true
  trigger:
    platform: event
    event_type: ios.action_fired
  condition:
    condition: template
    value_template: "{{ trigger.event.data.actionName.startswith('api:') }}"
  action:
    service_template: "{{ trigger.event.data.actionName.strip('api:').split('/', 1)[0] }}"
    data_template:
      entity_id: "{{ trigger.event.data.actionName.strip('api:').split('/', 1)[1] }}"
