- alias: kitch_light_temp_cold
  initial_state: True
  trigger:
    platform: state
    entity_id: light.main_kitchen_lights
    to: "on"
  condition:
    condition: state
    entity_id: group.kitchen_leds
    state: "on"
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_leds_super_bright

- alias: kitch_light_temp_warm_bright
  initial_state: True
  trigger:
    platform: state
    entity_id: light.main_kitchen_lights
    to: "off"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.kitchen_leds
          state: "on"
        - condition: state
          entity_id: binary_sensor.kitchen_motion_sensor_occupancy
          state: "on"
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_leds_bright

- alias: kitch_light_temp_warm_dim
  initial_state: True
  trigger:
    platform: state
    entity_id: light.main_kitchen_lights
    to: "off"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.kitchen_leds
          state: "on"
        - condition: state
          entity_id: binary_sensor.kitchen_motion_sensor_occupancy
          state: "off"
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_leds_dim
