# Announce if the kitchen plant needs watering when someone walks into the kitchen
- alias: kitchen_plant_notification
  initial_state: true
  trigger:
    platform: state
    entity_id: group.kitchen_motion_sensors
    to: "on"
  condition:
    condition: numeric_state
    entity_id: sensor.plant_sensor_a034_moisture
    below: 31
  action:
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.kitchen_display
        message: "<speak>Human. The kitchen plant needs watering.</speak>"
    - delay:
        minutes: 30
