# When there is no motion in the kitchen, providing the kitchen LED lights are on set them to a dim.
- alias: kitchen_motion_leds_down
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_occupancy
      to: "off"
  condition:
    condition: state
    entity_id: light.kitchen_left
    state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_left
        rgb_color: [255,200,145]
        brightness: 100
        transition: 30
    - service: light.turn_on
      data:
        entity_id: light.kitchen_right
        rgb_color: [255,200,145]
        brightness: 100
        transition: 30

# When there is motion in the kitchen, providing the kitchen LED lights are on set them to a bright warm light.
- alias: kitchen_motion_leds_up
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_occupancy
      to: "on"
  condition:
    condition: state
    entity_id: light.kitchen_left
    state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_left
        rgb_color: [255,200,145]
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.kitchen_right
        rgb_color: [255,200,145]
        brightness: 255

# If the kitchen lights are turned on and the kitchen is unoccupied (no motion) then go straight to the dim mode.
- alias: kitchen_motion_start_down_if_unoccupied
  initial_state: true
  trigger:
    platform: state
    entity_id: light.kitchen_right
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_left
        rgb_color: [255,200,145]
        brightness: 100
    - service: light.turn_on
      data:
        entity_id: light.kitchen_right
        rgb_color: [255,200,145]
        brightness: 100

# If the kitchen lights are turned on and the kitchen is occupied (motion detected) then go straight to the bright mode.
- alias: kitchen_motion_start_down_if_unoccupied
  initial_state: true
  trigger:
    platform: state
    entity_id: light.kitchen_right
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_left
        rgb_color: [255,200,145]
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.kitchen_right
        rgb_color: [255,200,145]
        brightness: 255