- alias: kitchen_switch
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_switch
    not_from:
      - "unavailable"
      - "unknown"
  action:
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_switch
      timeout:
        seconds: 0.5
    - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
        sequence:
          - service: light.toggle
            entity_id: light.kitchen_leds
      default:
        - service: light.toggle
          entity_id: light.main_kitchen_lights
