# # If the front door is opened (looks like someone is leaving) and the bedroom window is open (most likely thing left open) then send a notification to Adam if he's home.
# - alias: leaving_open_cover_warning_door_adam
#   initial_state: true
#   trigger:
#     platform: state
#     entity_id: binary_sensor.0x00158d0001a5e08d_contact
#     to: "on"
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: binary_sensor.0x00158d000222cb59_contact
#         state: "on"
#       - condition: state
#         entity_id: person.adam
#         state: "home"
#       # 30s Debounce
#       - condition: template
#         value_template: >
#           {% set automation_name = "leaving_open_cover_warning_door_adam" %}
#           {% set debounce_seconds = 30 %}
#           {{ 
#             (states.automation[automation_name].attributes.last_triggered == none) 
#             or (as_timestamp(state_attr('automation.' + automation_name, 'last_triggered')) < (as_timestamp(now()) - debounce_seconds))
#           }}
#   action:
#     - service: notify.mobile_app_dullage_s_iphone
#       data:
#         message: "Warning! The bedroom window is open!"
#         data:
#           push:
#             sound:
#               name: default
#               critical: 1
#               volume: 1.0

# # If the front door is opened (looks like someone is leaving) and the bedroom window is open (most likely thing left open) then send a notification to Leanne if she's home.
# - alias: leaving_open_cover_warning_door_leanne
#   initial_state: true
#   trigger:
#     platform: state
#     entity_id: binary_sensor.0x00158d0001a5e08d_contact
#     to: "on"
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: binary_sensor.0x00158d000222cb59_contact
#         state: "on"
#       - condition: state
#         entity_id: person.leanne
#         state: "home"
#       # 30s Debounce
#       - condition: template
#         value_template: >
#           {% set automation_name = "leaving_open_cover_warning_door_leanne" %}
#           {% set debounce_seconds = 30 %}
#           {{ 
#             (states.automation[automation_name].attributes.last_triggered == none) 
#             or (as_timestamp(state_attr('automation.' + automation_name, 'last_triggered')) < (as_timestamp(now()) - debounce_seconds))
#           }}
#   action:
#     - service: notify.mobile_app_iphone
#       data:
#         message: "Warning! The bedroom window is open!"
#         data:
#           push:
#             sound:
#               name: default
#               critical: 1
#               volume: 1.0

# If we've both left the house and a door or window is left open, send an iOS notification to both of us.
- alias: leaving_open_cover_warning_gps
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    from: "home"
    to: "not_home"
  condition:
    condition: or
    conditions:
      # Front Door
      - condition: state
        entity_id: binary_sensor.0x00158d0001a5e08d_contact
        state: "on"
      # Back Door
      - condition: state
        entity_id: binary_sensor.0x00158d00019f63a5_contact
        state: "on"
      # Patio Doors
      - condition: state
        entity_id: binary_sensor.0x00158d0001a67e20_contact
        state: "on"
      # Master Bedroom Window
      - condition: state
        entity_id: binary_sensor.0x00158d000222cb59_contact
        state: "on"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "STOP! You left a door or window open!"
    - service: notify.mobile_app_iphone
      data:
        message: "STOP! You left a door or window open!"
