# If we've both left the house and a door or window is left open, send an iOS notification to both of us.
- alias: leaving_open_cover_warning_gps
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    from: "home"
    to: "not_home"
  condition:
    condition: or
    conditions:
      # Front Door
      - condition: state
        entity_id: binary_sensor.front_door_contact
        state: "on"
      # Back Door
      - condition: state
        entity_id: binary_sensor.garden_door_contact
        state: "on"
      # Patio Doors
      - condition: state
        entity_id: binary_sensor.patio_doors_contact
        state: "on"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "STOP! You left a door or window open!"
    - service: notify.mobile_app_iphone
      data:
        message: "STOP! You left a door or window open!"
