# Toggle the bedroom lamps when the bedroom light switch is double toggled.
- alias: master_bedroom_switch_double_toggle
  initial_state: true
  trigger:
    platform: mqtt
    topic: automation
    payload: "master_bedroom_main"
  action:
    service: light.toggle
    entity_id: light.bedroom_lamps
