# Automate the bathroom lights based on Adam's normal workday routine.
- alias: morning_routine_adam
  initial_state: true
  trigger:
    # Going downstairs to feed the cat. The downstairs lights will be turned on automatically by another automation.
    platform: state
    entity_id: binary_sensor.stairs_motion_sensor_occupancy
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "05:50:00"
        before: "06:20:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: script.morning_routine
    # 2h Debounce
    - delay:
        hours: 2
