- alias: nfc_tags_frontroom
  initial_state: true
  trigger:
    platform: event
    event_type: tag_scanned
    event_data:
      tag_id: ed708c81-7452-431e-b669-367328001ad5
  action:
    service: light.toggle
    entity_id: light.front_room_lamp
