# Turn the office heater and the auto on automation off if the house is left unnocupied.
- alias: office_heater_location_safety
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
  condition:
    condition: template
    value_template: "{{ states('group.everyone') != 'home' }}"
  action:
    - service: climate.turn_off
      entity_id: climate.office_heater

# Just in case I forget, turn off the office heater at 5:30pm each day.
- alias: office_heater_time_safety
  initial_state: true
  trigger:
    platform: time
    at: "17:30:00"
  action:
    - service: climate.turn_off
      entity_id: climate.office_heater
