- alias: rain_guage_increment_counter
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.rain_sensor_contact
    from:
      - "on"
      - "off"
    to:
      - "on"
      - "off"
  action:
    service: counter.increment
    entity_id: counter.rain_sensor_flips
