# Saying "Hey Google, add beer to the shopping list" will trigger an IFTTT webhook which then (via this automation) adds the item "beer" to the Home Assistant shopping list.
- alias: shopping_list_google_assistant
  initial_state: true
  trigger:
    platform: event
    event_type: ifttt_webhook_received
  action:
    service: shopping_list.add_item
    data_template:
      name: "{{ trigger.event.data.item | title }}"

# # If Adam goes near any local supermarket, if there's anything on the shopping list, send him an iOS notification containing the list.
# - alias: shopping_list_enter_adam
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.adam
#       to: "Tesco"
#     - platform: state
#       entity_id: person.adam
#       to: "Sainsburys"
#     - platform: state
#       entity_id: person.adam
#       to: "Asda"
#     - platform: state
#       entity_id: person.adam
#       to: "Morrisons"
#   action:
#     - service: shell_command.shopping_list_enter_adam

# # If Leanne goes near any local supermarket, if there's anything on the shopping list, send her an iOS notification containing the list.
# - alias: shopping_list_enter_leanne
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.leanne
#       to: "Tesco"
#     - platform: state
#       entity_id: person.leanne
#       to: "Sainsburys"
#     - platform: state
#       entity_id: person.leanne
#       to: "Asda"
#     - platform: state
#       entity_id: person.leanne
#       to: "Morrisons"
#   action:
#     - service: shell_command.shopping_list_enter_leanne

# # When Adam leaves a local supermarket, ask him (via an iOS notification) if he wants to clear the shopping list (only if there is somthing on it).
# - alias: shopping_list_exit_adam
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.adam
#       from: "Tesco"
#     - platform: state
#       entity_id: person.adam
#       from: "Sainsburys"
#     - platform: state
#       entity_id: person.adam
#       from: "Asda"
#     - platform: state
#       entity_id: person.adam
#       from: "Morrisons"
#   action:
#     - service: shell_command.shopping_list_exit_adam

# # When Leanne leaves a local supermarket, ask her (via an iOS notification) if she wants to clear the shopping list (only if there is somthing on it).
# - alias: shopping_list_exit_leanne
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.leanne
#       from: "Tesco"
#     - platform: state
#       entity_id: person.leanne
#       from: "Sainsburys"
#     - platform: state
#       entity_id: person.leanne
#       from: "Asda"
#     - platform: state
#       entity_id: person.leanne
#       from: "Morrisons"
#   action:
#     - service: shell_command.shopping_list_exit_leanne

# # Clear the shopping list if either of us press the relevant button in the iOS notification.
# - alias: shopping_list_exit_action
#   initial_state: true
#   trigger:
#     platform: event
#     event_type: ios.notification_action_fired
#     event_data:
#       actionName: CLEAR_SHOPPING_LIST
#   action:
#     - service: shell_command.shopping_list_clear
