# Warn if the tablet battery is getting low.
- alias: tablet_battery_warning
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.sm_p610_battery_level
        below: 31
      - condition: state
        entity_id: person.adam
        state: "home"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Your tablet needs charging."
    - delay:
        minutes: 5
