- alias: video_call_lights_on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.video_call_lights
    to: "on"
  action:
    - service: scene.create
      data:
        scene_id: video_call_lights_previous_state
        snapshot_entities:
          - light.lodge_desk_left
          - light.lodge_desk_right
          - light.lodge_ceiling_2
    - service: light.turn_on
      entity_id: light.lodge_desk
      data:
        brightness: 255
        color_temp: 250
    - service: light.turn_on
      entity_id: light.lodge_ceiling_2
      data:
        brightness: 255
        color_temp: 250

- alias: video_call_lights_off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.video_call_lights
    to: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.video_call_lights_previous_state
    - service: scene.delete
      target:
        entity_id: scene.video_call_lights_previous_state

- alias: video_call_lights_auto_off
  initial_state: true
  trigger:
    platform: state
    entity_id: light.lodge_desk
    to: "off"
  condition:
    condition: state
    entity_id: input_boolean.video_call_lights
    state: "on"
  action:
    - service: automation.turn_off
      entity_id: automation.video_call_lights_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.video_call_lights
    - service: automation.turn_on
      entity_id: automation.video_call_lights_on
