- alias: webhook_download_complete
  initial_state: true
  trigger:
    platform: webhook
    webhook_id: !secret download_complete_webhook_id
    allowed_methods:
      - POST
    local_only: false
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data_template:
        message: >
          Download Complete: {{ trigger.json.message }}
