- alias: webhook_notify_adam
  initial_state: true
  trigger:
    platform: webhook
    webhook_id: !secret notify_adam_webhook_id
    allowed_methods:
      - POST
    local_only: false
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data_template:
        message: >
          {{ trigger.json.message }}
