scene.downstairs_general:
  name: Downstairs General
scene.front_room_dim:
  name: Front Room Dim
scene.downstairs_off:
  name: Downstairs Off
light.front_room_lamp:
  name: Front Room Lamp
script.going_out:
  name: Going Out Script
light.main_kitchen_lights:
  name: Kitchen Lights
light.garden_lights:
  name: Garden Lights
light.landing_light:
  name: Landing Light
light.bathroom_lights:
  name: Bathroom Lights
light.master_bedroom_main:
  name: Bedroom Lights
light.bedroom_lamps:
  name: Bedroom Lamps
input_boolean.all_av:
  name: TV
light.porch_light:
  name: Porch Light
light.entrance_light:
  name: Entrance Light
switch.coat_rack:
  name: Coat Rack Lights
light.dining_room_lamp:
  name: Dining Room Lamp
input_boolean.cartoons:
  name: Cartoons
