- platform: command_line
  name: rejected_front_door_per_hr
  command: "find /cctv/rejected -mmin -60 -type f -name '*Front Door*' | wc -l"
  unit_of_measurement: "ph"
  scan_interval: 600

- platform: command_line
  name: rejected_side_per_hr
  command: "find /cctv/rejected -mmin -60 -type f -name '*Side*' | wc -l"
  unit_of_measurement: "ph"
  scan_interval: 600

- platform: command_line
  name: rejected_garden_per_hr
  command: "find /cctv/rejected -mmin -60 -type f -name '*Garden*' | wc -l"
  unit_of_measurement: "ph"
  scan_interval: 600
