- platform: darksky
  api_key: !secret darksky_api_key
  units: uk2
  monitored_conditions:
    - precip_intensity
    - precip_probability
    - precip_intensity_max
    - temperature
    - wind_speed
    - wind_bearing
    - cloud_cover
    - minutely_summary
