- platform: mqtt
  state_topic: "temperature/loft"
  name: "Loft Temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "humidity/loft"
  name: "Loft Humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: tv_power_consumption
  state_topic: 2NICE-7/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: W

- platform: mqtt
  name: bedroom_blind_position
  state_topic: "de:66:92:69:03:8c/00001861-b87f-490c-92cb-11ba5ea5167c/00001525-b87f-490c-92cb-11ba5ea5167c"
  value_template: "{% set position = 100 - (value.split(',')[0] | int) %}{{ position }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: bedroom_blind_battery
  device_class: battery
  state_topic: "de:66:92:69:03:8c/BatteryService/BatteryLevel"
  availability_topic: "de:66:92:69:03:8c/Connected"
  value_template: "{{ [((value | int) * 1.2) | int, 100] | min }}"
  payload_available: "true"
  payload_not_available: "false"
  unit_of_measurement: "%"

- platform: mqtt
  name: ble2mqtt_uptime2
  state_topic: "BLE2MQTT-AAB8/Uptime"
  value_template: "{{ value | int }}"
  unit_of_measurement: "s"
