- platform: template
  sensors:
    ad_hoc_heating_time:
      friendly_name: "Set Time"
      value_template: "{% if states.input_number.ad_hoc_heating_time_hour.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.ad_hoc_heating_time_hour.state|round(0)|string }}:{% if states.input_number.ad_hoc_heating_time_minute.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.ad_hoc_heating_time_minute.state|round(0)|string }}"

    adam_badge:
      unit_of_measurement: Adam
      entity_id: person.adam
      friendly_name_template: >
        {% if is_state('person.adam', 'home') %}
          Home
        {% elif is_state('person.adam', 'not_home') %}
          Away
        {% else %}
          {{ states('person.adam') }}
        {% endif %}
      value_template: >
        {% if is_state('person.adam', 'home') %}
          Home
        {% elif is_state('person.adam', 'not_home') %}
          Away
        {% else %}
          {{ states('person.adam') }}
        {% endif %}
      entity_picture_template: https://www.gravatar.com/avatar/ab1e383c9a6fb394fe2afa5389c21657.jpg

    leanne_badge:
      unit_of_measurement: Leanne
      entity_id: person.leanne
      friendly_name_template: >
        {% if is_state('person.leanne', 'home') %}
          Home
        {% elif is_state('person.leanne', 'not_home') %}
          Away
        {% else %}
          {{ states('person.leanne') }}
        {% endif %}
      value_template: >
        {% if is_state('person.leanne', 'home') %}
          Home
        {% elif is_state('person.leanne', 'not_home') %}
          Away
        {% else %}
          {{ states('person.leanne') }}
        {% endif %}
      entity_picture_template: /local/leanne.jpg
