- name: porch_motion
  state_topic: "shellies/shelly1-227D0A/input/0"
  device_class: motion
  payload_on: "1"
  payload_off: "0"

- name: kitchen_switch
  state_topic: "shellies/shelly1-76F1C8/input/0"
  payload_on: "1"
  payload_off: "0"

- name: master_bedroom_switch
  state_topic: "shellies/shelly1-3494546A72BE/input/0"
  payload_on: "1"
  payload_off: "0"
