- name: Bathroom Mirror Lights
  command_topic: "shellies/shelly1-2272F1/relay/0/command"
  state_topic: "shellies/shelly1-2272F1/relay/0"
  payload_off: "off"
  payload_on: "on"
  retain: false

- name: Main Kitchen Lights
  command_topic: "shellies/shelly1-76F1C8/relay/0/command"
  state_topic: "shellies/shelly1-76F1C8/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false

- name: Front Room Lamp
  state_topic: "light/front_room_lamp/state"
  command_topic: "light/front_room_lamp"
  payload_off: "0"
  payload_on: "1"
  retain: false

- name: Master Bedroom Main
  command_topic: "light/master_bedroom_main"
  state_topic: "light/master_bedroom_main/state"
  payload_on: "1"
  payload_off: "0"
  retain: false

- name: Garden Lights
  command_topic: "shellies/shelly1-32CDCA/relay/0/command"
  state_topic: "shellies/shelly1-32CDCA/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false

- name: porch_light
  command_topic: "shellies/shelly1-227D0A/relay/0/command"
  state_topic: "shellies/shelly1-227D0A/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false

- name: entrance_light
  command_topic: "shellies/shelly1-76F1B6/relay/0/command"
  state_topic: "shellies/shelly1-76F1B6/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false
