- name: office_heater_energy
  unique_id: 8d1eee6a-ed94-4263-a9c8-057090867123
  state_topic: 2NICE-1/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: monitor_power_consumption
  unique_id: 19dd225d-c898-43a4-b839-78cb832aaa6a
  state_topic: 2NICE-2/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: W

# 2NICE-3 = Master Bedroom Air Freshener

# 2NICE-4 = Air Freshener

- name: microwave_energy
  unique_id: 3a5fe68c-3c47-44c0-9dcd-4ea6eba324ed
  state_topic: 2NICE-5/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

# 2NICE-6 = Unused

# 2NICE-7 = Unused

# 2NICE-8 = Rainbow Light

# LB-1 = Electric Blanket

# LB-2 = Blue's Night Light

# LB-3 = Unused
