- name: office_heater_energy
  unique_id: 8d1eee6a-ed94-4263-a9c8-057090867123
  state_topic: 2NICE-1/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: sprinklers_energy
  unique_id: 3652a46f-f719-423f-81bd-22fe546cf84c
  state_topic: 2NICE-2/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: server_cupboard_energy
  unique_id: 0f7df323-ba25-4075-a33c-81aa2368ebf2
  state_topic: 2NICE-3/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: server_cupboard_power_consumption
  unique_id: 7d5a2b71-8cfd-442c-9488-ba3000bf45c7
  state_topic: 2NICE-3/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: W

- name: microwave_energy
  unique_id: 3a5fe68c-3c47-44c0-9dcd-4ea6eba324ed
  state_topic: 2NICE-5/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

# - name: air_conditioner_energy
#   unique_id: ac13a283-7ac5-4023-be62-cf5bb683c8da
#   state_topic: 2NICE-6/tele/SENSOR
#   value_template: '{{ value_json["ENERGY"]["Total"] }}'
#   unit_of_measurement: kWh
#   device_class: energy
#   state_class: total_increasing

# - name: air_conditioner_power_consumption
#   unique_id: 2a847ee7-61c2-4125-8a34-ae522ea551cc
#   state_topic: 2NICE-6/tele/SENSOR
#   value_template: '{{ value_json["ENERGY"]["Power"] }}'
#   unit_of_measurement: W

- name: blues_fan_energy
  unique_id: 266bc096-882e-4848-92fc-8d8eed7ae2aa
  state_topic: 2NICE-6/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: blues_fan_power_consumption
  unique_id: 2b9f1c35-4250-4926-a53d-e68cb7119cce
  state_topic: 2NICE-6/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: W

# - name: fridge_energy
#   unique_id: 33db4c34-f10d-4b4a-a27e-6041308bbde3
#   state_topic: 2NICE-7/tele/SENSOR
#   value_template: '{{ value_json["ENERGY"]["Total"] }}'
#   unit_of_measurement: kWh
#   device_class: energy
#   state_class: total_increasing

# - name: fridge_consumption
#   unique_id: d5c2cf44-5da8-4cd3-a570-37c98c4fe090
#   state_topic: 2NICE-7/tele/SENSOR
#   value_template: '{{ value_json["ENERGY"]["Power"] }}'
#   unit_of_measurement: W

- name: bedroom_fan_energy
  unique_id: 9036cc19-aeeb-4f4d-bb2a-9acbb61e55a1
  state_topic: 2NICE-8/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing

- name: bedroom_fan_power_consumption
  unique_id: 39812578-baa4-4e2f-b7f6-e29e1afd6b1b
  state_topic: 2NICE-8/tele/SENSOR
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: W
