- name: office_heater
  command_topic: 2NICE-1/cmnd/POWER
  state_topic: 2NICE-1/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: sprinklers
  command_topic: 2NICE-2/cmnd/POWER
  state_topic: 2NICE-2/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

# 2NICE-3 = Server Cupboard

- name: air_freshener
  command_topic: 2NICE-4/cmnd/POWER
  state_topic: 2NICE-4/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: microwave
  command_topic: 2NICE-5/cmnd/POWER
  state_topic: 2NICE-5/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

# 2NICE-6 = Unused

# 2NICE-7 = Unused

- name: rainbow_light
  command_topic: 2NICE-8/cmnd/POWER
  state_topic: 2NICE-8/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: electric_blanket
  command_topic: local-bytes/LB-1/cmnd/POWER
  state_topic: local-bytes/LB-1/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: blues_night_light
  command_topic: local-bytes/LB-2/cmnd/POWER
  state_topic: local-bytes/LB-2/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

# LB-3 = Unused
