- name: office_heater
  command_topic: 2NICE-1/cmnd/POWER
  state_topic: 2NICE-1/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: sprinklers
  command_topic: 2NICE-2/cmnd/POWER
  state_topic: 2NICE-2/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

# 2NICE-3 = Server Cupboard

- name: air_freshener
  command_topic: 2NICE-4/cmnd/POWER
  state_topic: 2NICE-4/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: microwave
  command_topic: 2NICE-5/cmnd/POWER
  state_topic: 2NICE-5/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- name: blues_fan
  command_topic: 2NICE-6/cmnd/POWER
  state_topic: 2NICE-6/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

- # 2NICE-7 = Unused

- name: bedroom_fan
  command_topic: 2NICE-8/cmnd/POWER
  state_topic: 2NICE-8/stat/POWER
  payload_on: "ON"
  payload_off: "OFF"

# - LB-1 = Unused

# - LB-2 = Unused

# - LB-3 = Unused
