maestro_corner_lamp:
  name: "Corner Lamp - Maestro"
  options:
    - "Off"
    - "Fire"
    - "Police"
    - "Sparkle"

maestro_stairs:
  name: "Stairs - Maestro"
  options:
    - "Off"
    - "Fire"
    - "Police"
    - "Sparkle"
    - "Startup"
    - "Shutdown"
