maestro_corner_lamp:
  name: "Corner Lamp - Maestro"
  options:
    - "Off"
    - "Fire"
    - "Police"
    - "Sparkle"
    - "Bouncing Ball"
    - "Bouncing Balls"

maestro_stairs:
  name: "Stairs - Maestro"
  options:
    - "Off"
    - "Fire"
    - "Police"
    - "Sparkle"
    - "Bouncing Ball"
    - "Bouncing Balls"
    - "Startup"
    - "Shutdown"
