stairs_mode:
  name: Stairs Mode
  options:
    - "Select..."
    - "Warm Light"
    - "Strobe"
    - "Fire"
    - "Colour Phase"
    - "Sparkle"
    - "Shoot / Drip"
    - "Rain"
    - "Rainbow 1"
    - "Rainbow 2"
    - "Stepped"
    - "Startup"
    - "Shutdown"
    - "All On"
  initial: "Select..."
