everyone:
  name: Everyone
  entities:
    - person.adam
    - person.leanne

# A group containing all lights including lights that are in the switch domain. 
all_lights:
  name: All Lights
  entities:
    - switch.coat_rack
    - light.entrance_light
    - light.dining_room_lamp
    - light.corner_lamp
    - light.tv_left
    - light.tv_top
    - light.tv_right
    - light.frontroom_under_tv
    - light.dining_room_lamp
    - light.main_kitchen_lights
    - light.front_room_lamp
    - light.kitchen_left_top
    - light.kitchen_left_bottom
    - light.kitchen_right_top
    - light.kitchen_right_bottom
    - light.stairs
    - light.landing_light
    - light.bathroom_lights
    - light.bathroom_mirror_lights
    - light.master_bedroom_main
    - light.bedroom_lamps
    - light.garden_lights

# Everything that should be turned off when leaving
everything:
  name: Everything
  entities:
    - group.all_lights
    - input_boolean.all_av

living_room:
  name: Living Room
  entities:
    - light.front_room_lamp
    - group.tv

kitchen_leds:
  name: Kitchen LEDs
  entities:
    - light.kitchen_left_bottom
    - light.kitchen_left_top
    - light.kitchen_right_bottom
    - light.kitchen_right_top

kitchen_leds_bottom:
  name: Bottom Kitchen LEDs
  entities:
    - light.kitchen_left_bottom
    - light.kitchen_right_bottom

kitchen_leds_top:
  name: Top Kitchen LEDs
  entities:
    - light.kitchen_left_top
    - light.kitchen_right_top

kitchen:
  name: Kitchen
  entities:
    - light.main_kitchen_lights
    - group.kitchen_leds

dining_room:
  name: Dining Room
  entities:
    - light.dining_room_lamp
    - light.entrance_light
    - light.corner_lamp

tv:
  name: TV
  entities:
    - light.tv_left
    - light.tv_top
    - light.tv_right
    - light.frontroom_under_tv

downstairs_ex_stairs:
  name: Downstairs Excluding Stairs
  entities:
    - group.living_room
    - group.kitchen
    - group.dining_room

downstairs:
  name: Downstairs
  entities:
    - group.downstairsExcStairs
    - light.stairs

pi_holes:
  name: Pi-holes
  entities:
    - switch.pi_hole
    - switch.pi_hole2
