everyone:
  name: Everyone
  entities:
    - person.adam
    - person.leanne

# Includes switches that are lights but not ones that aren't.
biglightgroup:
  name: The Big Light Group
  entities:
    - group.all_lights
    - switch.christmas_tree
    - switch.path_lights

# Everything that should be turned off when leaving
everything:
  name: Everything
  entities:
    - group.all_lights
    - switch.christmas_tree

living_room:
  name: Living Room
  entities:
    - light.front_room_lamp
    - group.tv

kitchen_low:
  name: Kitchen Low Lights
  entities:
    - light.kitchen_left
    - light.kitchen_right

kitchen:
  name: Kitchen
  entities:
    - light.main_kitchen_lights
    - group.kitchen_low

dining_room:
  name: Dining Room
  entities:
    - light.dining_room_lamp
    - switch.christmas_tree
    - light.entrance_light

tv:
  name: TV
  entities:
    - light.tv_left
    - light.tv_top
    - light.tv_right
    - light.frontroom_under_tv

downstairs_ex_stairs:
  name: Downstairs Excluding Stairs
  entities:
    - group.living_room
    - group.kitchen
    - group.dining_room

downstairs:
  name: Downstairs
  entities:
    - group.downstairsExcStairs
    - light.stairs
