everyone:
  name: Everyone
  entities:
    - person.adam
    - person.leanne

# Everything that should be turned off when leaving
everything:
  name: Everything
  entities:
    - switch.coat_rack
    - light.entrance_light
    - light.dining_room_lamp
    - light.tv_left
    - light.tv_top
    - light.tv_right
    - light.frontroom_under_tv
    - light.dining_room_lamp
    - light.main_kitchen_lights
    - light.front_room_lamp
    - light.kitchen_left
    - light.kitchen_right
    - light.stairs
    - light.landing_light
    - light.bathroom_lights
    - light.bathroom_mirror_lights
    - light.master_bedroom_main
    - light.bedroom_lamps
    - light.garden_lights

living_room:
  name: Living Room
  entities:
    - light.front_room_lamp
    - group.tv

kitchen_low:
  name: Kitchen Low Lights
  entities:
    - light.kitchen_left
    - light.kitchen_right

kitchen:
  name: Kitchen
  entities:
    - light.main_kitchen_lights
    - group.kitchen_low

dining_room:
  name: Dining Room
  entities:
    - light.dining_room_lamp
    - light.entrance_light

tv:
  name: TV
  entities:
    - light.tv_left
    - light.tv_top
    - light.tv_right
    - light.frontroom_under_tv

downstairs_ex_stairs:
  name: Downstairs Excluding Stairs
  entities:
    - group.living_room
    - group.kitchen
    - group.dining_room

downstairs:
  name: Downstairs
  entities:
    - group.downstairsExcStairs
    - light.stairs
