healthcheck: "curl --retry 3 https://hc-ping.com/c56f4efa-bf94-4112-9a4d-2ceb506891ed"
pause_healthcheck: !secret pause_healthcheck_shell_command
render_voice_assistant_config: python3 /config/config/voice_assistants/voice_assistant_config.py
