- alias: adam_location_update_message_home
  initial_state: true
  trigger:
    platform: state
    entity_id: group.adam
    to: "home"
  action:
    - service: notify.ios_adams_iphone
      data_template:
        message: "Hello"

- alias: adam_location_update_message_away
  initial_state: true
  trigger:
    platform: state
    entity_id: group.adam
    to: "not_home"
  action:
    - service: notify.ios_adams_iphone
      data_template:
        message: "Goodbye"