# Ad-Hoc Heating On Alarm      
# https://community.home-assistant.io/t/creating-a-alarm-clock/410/105)
- alias: 'triggerheatingon'
  initial_state: False
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: template
      value_template: '{{ now().hour == (states.input_number.heatingonhour.state  | round(0))  and  now().minute == (states.input_number.heatingonminutes.state  | round(0) )  }}'
  action:
    - service: climate.set_temperature
      data:
        temperature: 21
    - service: homeassistant.turn_off
      data:
        entity_id: automation.triggerheatingon