- alias: alarm
  initial_state: true
  trigger:
  # Front Door
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
      to: 'on'
  # Back Door
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00019f63a5
      to: 'on'
  # Patio Doors
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001a67e20
      to: 'on'
  # Master Bedroom Window
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000222cb59
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
      - condition: template
        value_template: "{{ states('person.leanne') != 'home' }}"
  action:
    - service: notify.ios_adams_iphone
      data:
        message: "Alarm: Door / Window Opened!"
    - service: notify.ios_leannes_iphone
      data:
        message: "Alarm: Door / Window Opened!"
