# Adams Reminders
- alias: arrival_reminder_adam
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
    to: 'on'
  condition:
    condition: and
    conditions:    
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'on'
      - condition: template
        value_template: "{{ states.input_text.arrival_reminder_adam.state != '' }}"
  action:
    - delay:
        seconds: 10
    - service: mqtt.publish
      data_template:
        topic: "message"
        payload: "Adams's Reminder: {{ states.input_text.arrival_reminder_adam.state }}"
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.google_homes
        message: "<speak>Reminder for Adam. {{ states.input_text.arrival_reminder_adam.state }}</speak>"
    - service: input_text.set_value
      data:
        entity_id: input_text.arrival_reminder_adam
        value: ""

# Leannes Reminders
- alias: arrival_reminder_leanne
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
    to: 'on'
  condition:
    condition: and
    conditions:    
      - condition: state
        entity_id: input_boolean.queue_home_leanne
        state: 'on'
      - condition: template
        value_template: "{{ states.input_text.arrival_reminder_leanne.state != '' }}"
  action:
    - delay:
        seconds: 10
    - service: mqtt.publish
      data_template:
        topic: "message"
        payload: "Leanne's Reminder: {{ states.input_text.arrival_reminder_leanne.state }}"
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.google_homes
        message: "<speak>Reminder for Leanne. {{ states.input_text.arrival_reminder_leanne.state }}</speak>"
    - service: input_text.set_value
      data:
        entity_id: input_text.arrival_reminder_leanne
        value: ""