# Bathroom Mirror Lights <=> Main Bathroom Lights
- alias: bathroom_mirror_lights_on
  initial_state: true
  trigger:
    platform: state
    entity_id: light.bathroom_lights
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom_mirror_lights
- alias: bathroom_mirror_lights_off
  initial_state: true
  trigger:
    platform: state
    entity_id: light.bathroom_lights
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_mirror_lights

# Bathroom Mirror Night Light
- alias: bathroom_night_light_on
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015e6be1
    to: 'on'
  condition:
    condition: and
    conditions:
      # - condition: time
        # after: '23:00:00'
        # before: '06:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.bathroom_mirror_lights
- alias: bathroom_night_light_off
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015e6be1
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.bathroom_lights
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: light.turn_off
    entity_id: light.bathroom_mirror_lights

# Timeout
- alias: bathroom_lights_timeout
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015e6be1
    to: 'off'
    for:
      minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.bathroom_lights
    - service: light.turn_off
      entity_id: light.bathroom_mirror_lights