- alias: misc_switch_1
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128c313
      click_type: single
  action:
    service: light.toggle
    entity_id: light.bedroom_lamps

- alias: misc_switch_2
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128c313
      click_type: double
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lamps
      xy_color: [0.50, 0.42]

- alias: misc_switch_3
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128c313
      click_type: long_click_press
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lamps
      xy_color: [0.638, 0.288]
