- alias: bedtime
  initial_state: true
  trigger:
    platform: state
    entity_id: group.downstairs
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: time
    after: '21:00:00'
  action:
    - service: climate.set_temperature
      data:
        temperature: 9
    - service: switch.turn_off
      entity_id: switch.echo_amplifier