- alias: chromecast_input_on
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: 'idle'
  action:
    service: script.input_chromecast
    
- alias: chromecast_input_off
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  action:
    service: script.input_sky