- alias: screen_on
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000223abef
    to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "wallpanel/diningroom/command"
      payload: "{'wake': true}"
