# Doorbell
- alias: doorbell
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002135d1d
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002135d1d
        click_type: double
  condition:
    condition: template
    value_template: "{{ (states.automation.doorbell.attributes.last_triggered == none) or (as_timestamp(state_attr('automation.doorbell', 'last_triggered')) < (as_timestamp(now()) - 5)) }}"
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34:ce:00:8c:05:b9
        ringtone_id: 10
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.google_homes
        message: "<speak>There is someone at the front door.</speak>"
    - service: shell_command.blink
    - service: mqtt.publish
      data:
        topic: screenpi
        payload: 2
    - delay:
        minutes: 3
    - service: mqtt.publish
      data:
        topic: screenpi
        payload: 1