# Turn the downstairs amp on if Adam comes home
- alias: adam_arriving_echo_amp_on
  initial_state: true
  trigger:
    platform: state
    entity_id: group.adam
    to: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.echo_amplifier
      
# Turn the downstairs amp on if Lea comes home
- alias: lea_arriving_echo_amp_on
  initial_state: true
  trigger:
    platform: state
    entity_id: group.leanne
    to: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.echo_amplifier
     
# Turn downstairs amp off at midnight (just a backup)
- alias: midnight_echo_amp_off
  initial_state: true
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.echo_amplifier
      
# Turn downstairs amp on at 7am
- alias: 7am_echo_amp_on
  initial_state: true
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.leanne
        state: 'home'  
      - condition: state
        entity_id: group.adam
        state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.echo_amplifier