- alias: front_room_switch_1
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000204a3c3
      click_type: single
  action:
    service: light.toggle
    entity_id: light.front_room_lamp

- alias: front_room_switch_2
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000204a3c3
      click_type: double
  action:
    service: script.normal_av