- alias: garden_lights_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00019f63a5
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001a67e20
      to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.garden_lights

- alias: garden_lights_off_kitchen_door
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019f63a5
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001a67e20
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.garden_lights

- alias: garden_lights_off_patio_doors
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a67e20
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: binary_sensor.door_window_sensor_158d00019f63a5
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.garden_lights