# Nick
- alias: nick_warning
  initial_state: true
  trigger: 
    platform: state
    entity_id: device_tracker.nicksiphone
    to: 'home'
  action:
    - service: notify.ios_adams_iphone
      data_template:
        message: "Nick is here!"
    - service: notify.ios_leannes_iphone
      data_template:
        message: "Nick is here!"

- alias: welcome_nick
  initial_state: true
  trigger: 
    platform: state
    entity_id: device_tracker.nicksiphone
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'off'
      - condition: state
        entity_id: input_boolean.queue_home_lea
        state: 'off'
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'off' }}"
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.front_room_speaker
        message: "<speak>Welcome Smiler</speak>"

# Yib
- alias: yib_warning
  initial_state: true
  trigger: 
    platform: state
    entity_id: device_tracker.livsgalaxy
    to: 'home'
  action:
    - service: notify.ios_adams_iphone
      data_template:
        message: "Yib is here!"
    - service: notify.ios_leannes_iphone
      data_template:
        message: "Yib is here!"

- alias: welcome_yib
  initial_state: true
  trigger: 
    platform: state
    entity_id: device_tracker.livsgalaxy
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'off'
      - condition: state
        entity_id: input_boolean.queue_home_lea
        state: 'off'
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'off' }}"
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.front_room_speaker
        message: "<speak>Welcome Yib</speak>"