- alias: hdmi_input_select
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.hdmi_input
  action:
    - service_template: >
        {% if trigger.to_state.state == 'Sky Box' %}
          script.input_sky
        {% elif trigger.to_state.state == 'Chromecast' %}
          script.input_chromecast
        {% elif trigger.to_state.state == 'Apple TV' %}
          script.input_apple_tv
        {% elif trigger.to_state.state == 'Xbox' %}
          script.input_xbox
        {% elif trigger.to_state.state == 'Guest HDMI' %}
          script.input_guest
        {% endif %}
