# healthchecks.io
- alias: healthcheck
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: "/1"
  action:
    service: shell_command.healthcheck

- alias: pause_healthcheck
  initial_state: true
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: shell_command.pause_healthcheck
