- alias: "Leanne (Notify Adam)"
  initial_state: false
  trigger:
    platform: state
    entity_id: person.leanne
    to: "home"
  action:
    - service: notify.mobile_app_dullage_s_iphone
      data:
        message: "Leanne is Home"
    - service: automation.turn_off
      entity_id: automation.leanne_notify_adam

- alias: "Adam (Notify Leanne)"
  initial_state: false
  trigger:
    platform: state
    entity_id: person.adam
    to: "home"
  action:
    - service: notify.mobile_app_iphone
      data:
        message: "Adam is Home"
    - service: automation.turn_off
      entity_id: automation.adam_notify_leanne
