################
## DOWNSTAIRS ##
################

- alias: downstairs_volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.downstairs_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs_speakers
      volume_level: "{{ trigger.to_state.state }}"

- alias: downstairs_volume_slider_update
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.downstairs_speakers
  condition:
    condition: template
    value_template: "{{ states.media_player.downstairs_speakers.attributes.volume_level is defined }}"
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.downstairs_volume
    - service: input_number.set_value
      data_template:
        entity_id: input_number.downstairs_volume
        value: "{{ states.media_player.downstairs_speakers.attributes.volume_level }}"
    - service: automation.turn_on
      data:
        entity_id: automation.downstairs_volume

################
## FRONT ROOM ##
################

- alias: front_room_volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.front_room_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.front_room_speakers
      volume_level: "{{ trigger.to_state.state }}"

- alias: front_room_volume_slider_update
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.front_room_speakers
  condition:
    condition: template
    value_template: "{{ states.media_player.front_room_speakers.attributes.volume_level is defined }}"
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.front_room_volume
    - service: input_number.set_value
      data_template:
        entity_id: input_number.front_room_volume
        value: "{{ states.media_player.front_room_speakers.attributes.volume_level }}"
    - service: automation.turn_on
      data:
        entity_id: automation.front_room_volume

##############
## UPSTAIRS ##
##############

- alias: upstairs_volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.upstairs_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.upstairs_speakers
      volume_level: "{{ trigger.to_state.state }}"

- alias: upstairs_volume_slider_update
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.upstairs_speakers
  condition:
    condition: template
    value_template: "{{ states.media_player.upstairs_speakers.attributes.volume_level is defined }}"
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.upstairs_volume
    - service: input_number.set_value
      data_template:
        entity_id: input_number.upstairs_volume
        value: "{{ states.media_player.upstairs_speakers.attributes.volume_level }}"
    - service: automation.turn_on
      data:
        entity_id: automation.upstairs_volume

#################
## WHOLE HOUSE ##
#################

- alias: whole_house_volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.whole_house_volume
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.whole_house_2
        volume_level: "{{ trigger.to_state.state }}"
    # Downstairs
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.downstairs_speakers
        volume_level: "{{ trigger.to_state.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.downstairs_volume
        value: "{{ trigger.to_state.state }}"
    # Front Room
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.front_room_speakers
        volume_level: "{{ trigger.to_state.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.front_room_volume
        value: "{{ trigger.to_state.state }}"
    # Upstairs
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.upstairs_speakers
        volume_level: "{{ trigger.to_state.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.upstairs_volume
        value: "{{ trigger.to_state.state }}"

- alias: whole_house_volume_slider_update
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.whole_house_2
  condition:
    condition: template
    value_template: "{{ states.media_player.whole_house_2.attributes.volume_level is defined }}"
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.whole_house_volume
    - service: input_number.set_value
      data_template:
        entity_id: input_number.whole_house_volume
        value: "{{ states.media_player.whole_house_2.attributes.volume_level }}"
    - service: automation.turn_on
      data:
        entity_id: automation.whole_house_volume
#######################
## HIDE / SHOW GROUP ##
#######################

# - alias: house_audio_volume_group_hide
# initial_state: true
# trigger:
# platform: state
# entity_id: media_player.downstairs_speakers, media_player.front_room_speakers, media_player.upstairs_speakers, media_player.whole_house_2
# condition:
# condition: and
# conditions:
# - condition: state
# entity_id: media_player.downstairs_speakers
# state: ""
