- alias: "Ambilight Mode"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.hyperion
  action:
    - service_template: >
        {% if trigger.to_state.state == 'Backlight' %}
          shell_command.h_backlight
        {% elif trigger.to_state.state == 'Ambilight' %}
          shell_command.h_on
        {% elif trigger.to_state.state == 'Knight Rider' %}
          shell_command.h_knight_rider
        {% elif trigger.to_state.state == 'Mood Blobs Blue' %}
          shell_command.h_mood_blobs_blue
        {% elif trigger.to_state.state == 'Mood Blobs Cold' %}
          shell_command.h_mood_blobs_cold
        {% elif trigger.to_state.state == 'Mood Blobs Full Color' %}
          shell_command.h_mood_blobs_full_color
        {% elif trigger.to_state.state == 'Mood Blobs Green' %}
          shell_command.h_mood_blobs_green
        {% elif trigger.to_state.state == 'Mood Blobs Rainbow' %}
          shell_command.h_rainbow_mood
        {% elif trigger.to_state.state == 'Mood Blobs Red' %}
          shell_command.h_mood_blobs_red
        {% elif trigger.to_state.state == 'Mood Blobs Warm' %}
          shell_command.h_mood_blobs_warm
        {% elif trigger.to_state.state == 'Rainbow Swirl' %}
          shell_command.h_rainbow_swirl
        {% elif trigger.to_state.state == 'Snake' %}
          shell_command.h_snake
        {% elif trigger.to_state.state == 'Strobe Blue' %}
          shell_command.h_strobe_blue
        {% elif trigger.to_state.state == 'Strobe Raspberry' %}
          shell_command.h_strobe_raspberry
        {% elif trigger.to_state.state == 'Strobe White' %}
          shell_command.h_strobe_white
        {% elif trigger.to_state.state == 'Cinema Dim Lights' %}
          shell_command.h_cinema_dim_lights
        {% elif trigger.to_state.state == 'Cinema Brighten Lights' %}
          shell_command.h_cinema_brighten_lights
        {% elif trigger.to_state.state == 'Police Lights Single' %}
          shell_command.h_police_lights_single
        {% elif trigger.to_state.state == 'Police Lights Solid' %}
          shell_command.h_police_lights_solid
        {% elif trigger.to_state.state == 'Random' %}
          shell_command.h_random
        {% elif trigger.to_state.state == 'Running Dots' %}
          shell_command.h_running_dots
        {% elif trigger.to_state.state == 'System Shutdown' %}
          shell_command.h_system_shutdown
        {% elif trigger.to_state.state == 'Sparks Color' %}
          shell_command.h_sparks_color
        {% elif trigger.to_state.state == 'Sparks' %}
          shell_command.h_sparks
        {% elif trigger.to_state.state == 'Color Traces' %}
          shell_command.h_color_traces
        {% else %}
        {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.hyperion
        option: 'Select...'