- alias: ambilight_on
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.ambilight_power
    to: 'on'
  action:
    - service: script.hyperion_service_start
    - delay:
        seconds: 3
    - service: shell_command.h_backlight

- alias: ambilight_off
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.ambilight_power
    to: 'off'
  action:
    service: script.hyperion_service_stop