- alias: ios_hdmi_input
  initial_state: true
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "hdmi"
  action:
    service: input_select.select_next
    entity_id: input_select.hdmi_input
