- alias: "Kitchen Mode"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.kitchen_mode
  action:
    - service: mqtt.publish
      data_template:
        topic: "light/kitchen_left"
        payload: >
          {% if trigger.to_state.state == 'Warm Light' %}
            {0:2,2:[255,147,41]}
          {% elif trigger.to_state.state == 'Dim Light' %}
            {0:2,2:[26,15,4]}
          {% elif trigger.to_state.state == 'Strobe' %}
            {0:3}
          {% elif trigger.to_state.state == 'Fire' %}
            {0:4,3:55}
          {% elif trigger.to_state.state == 'Colour Phase' %}
            {0:5,3:100}
          {% elif trigger.to_state.state == 'Sparkle' %}
            {0:6,2:[50,50,50],3:0,4:2,5:60}
          {% elif trigger.to_state.state == 'Shoot / Drip' %}
            {0:7,2:[255,147,41],8:0,10:1,9:30,5:0,4:55,3:0,12:0,7:0}
          {% elif trigger.to_state.state == 'Rain' %}
            {0:8,11:600,3:1}
          {% else %}
            {}
          {% endif %}
        retain: false
    - service: mqtt.publish
      data_template:
        topic: "light/kitchen_right"
        payload: >
          {% if trigger.to_state.state == 'Warm Light' %}
            {0:2,2:[255,147,41]}
          {% elif trigger.to_state.state == 'Dim Light' %}
            {0:2,2:[26,15,4]}
          {% elif trigger.to_state.state == 'Strobe' %}
            {0:3}
          {% elif trigger.to_state.state == 'Fire' %}
            {0:4,3:55}
          {% elif trigger.to_state.state == 'Colour Phase' %}
            {0:5,3:100}
          {% elif trigger.to_state.state == 'Sparkle' %}
            {0:6,2:[50,50,50],3:0,4:2,5:60}
          {% elif trigger.to_state.state == 'Shoot / Drip' %}
            {0:7,2:[255,147,41],8:0,10:1,9:30,5:0,4:55,3:0,12:0,7:0}
          {% elif trigger.to_state.state == 'Rain' %}
            {0:8,11:600,3:1}
          {% else %}
            {}
          {% endif %}
        retain: false
    - service: input_select.select_option
      data:
        entity_id: input_select.kitchen_mode
        option: 'Select...'    