- alias: bothLeftEchoAmplifier
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.downstairs_amplifier