# Arriving
- alias: adam_home_lights
  initial_state: true
  trigger:
    platform: state
    entity_id: group.adam
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.leanne
        state: 'not_home'
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - service: scene.turn_on
      entity_id: scene.downstairs_general

- alias: lea_home_lights
  initial_state: true
  trigger:
    platform: state
    entity_id: group.leanne
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.adam
        state: 'not_home'
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - service: scene.turn_on
      entity_id: scene.downstairs_general
         
# Leaving
- alias: bothLeftLights
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
  condition:
    condition: state
    entity_id: group.biglightgroup
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: notify.telegram
      data:
        message: "You left lights on! But don't worry, I've turned them off for you!"