# If the Unifi tracker arrives, set the app tracker to arrived.
- alias: location_cleanup2_adam
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.dullagesiphone
      to: 'home'
  # Only step in if we need to
  condition:
    condition: template
    value_template: "{{ states('device_tracker.adams_iphone') != 'home' }}"
  action:
    - service: device_tracker.see
      data:
        dev_id: adams_iphone
        location_name: home
   # Debug
    - service: notify.ios_adams_iphone
      data:
        message: "Unifi stepped in for Adam's location."
        
- alias: location_cleanup2_leanne
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.iphone
      to: 'home'
  # Only step in if we need to
  condition:
    condition: template
    value_template: "{{ states('device_tracker.leannes_iphone') != 'home' }}"
  action:
    - service: device_tracker.see
      data:
        dev_id: leannes_iphone
        location_name: home
   # Debug
    - service: notify.ios_adams_iphone
      data:
        message: "Unifi stepped in for Leanne's location."
