- alias: bothLeftHeating
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '15:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.house_thermostat_target
        above: 10
  action:
    - service: climate.set_temperature
      data:
        temperature: 9
        
- alias: heating_warning
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
      # - condition: time
        # weekday:
          # - sat
          # - sun
      - condition: numeric_state
        entity_id: sensor.house_thermostat_target
        above: 9
  action:
    - service: notify.ios_adams_iphone
      data:
        message: "Warning: The heating is still on. Turn it off?"
        data:
          push:
            category: weekend_heating_warning
    - service: notify.ios_leannes_iphone
      data:
        message: "Warning: The heating is still on. Turn it off?"
        data:
          push:
            category: weekend_heating_warning
          
- alias: notification_action_heating_off
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: HEATING_TURN_OFF
  action:
    - service: climate.set_temperature
      data:
        temperature: 9