# Arriving
- alias: adam_home_lights
  initial_state: true
  trigger:
    platform: state
    entity_id: person.adam
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: template
        value_template: "{{ states('person.leanne') != 'home' }}"
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - service: scene.turn_on
      entity_id: scene.downstairs_general

- alias: lea_home_lights
  initial_state: true
  trigger:
    platform: state
    entity_id: person.leanne
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
  action:
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'on' }}"
    - service: scene.turn_on
      entity_id: scene.downstairs_general
         
# Leaving
- alias: bothLeftLights
  initial_state: true
  trigger:
    platform: state
    entity_id: group.everyone
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('group.everyone') != 'home' }}"
      - condition: state
        entity_id: group.biglightgroup
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    # - service: notify.ios_adams_iphone
      # data:
        # message: "You left lights on! But don't worry, I've turned them off for you!"
    # - service: notify.ios_leannes_iphone
      # data:
        # message: "You left lights on! But don't worry, I've turned them off for you!"