- alias: microwave_reset
  initial_state: true
  trigger:
    platform: time
    at: "00:59:50"
  action:
    - service: switch.turn_off
      entity_id: switch.microwave
    - delay:
        seconds: 10
    - service: switch.turn_on
      entity_id: switch.microwave
