- alias: screen_on
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000223abef
    to: 'on'
  action:
    service: shell_command.screen_on
- alias: screen_off
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000223abef
    to: 'off'
  action:
    service: shell_command.screen_off