- alias: voice_shopping_list
  initial_state: true
  trigger: 
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service: shopping_list.add_item
    data_template:
      name: '{{ trigger.event.data.item }}'
