- alias: "Stair Mode"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.stairs_mode
  action:
    - service: mqtt.publish
      data_template:
        topic: "light/stairs"
        payload: >
          {% if trigger.to_state.state == 'Warm Light' %}
            {0:2,2:[255,147,41]}
          {% elif trigger.to_state.state == 'Strobe' %}
            {0:3}
          {% elif trigger.to_state.state == 'Fire' %}
            {0:4}
          {% elif trigger.to_state.state == 'Colour Phase' %}
            {0:5,3:100}
          {% elif trigger.to_state.state == 'Sparkle' %}
            {0:6,2:[50,50,50],3:0,4:5,5:0}
          {% elif trigger.to_state.state == 'Shoot / Drip' %}
            {0:7,2:[255,147,41],8:0,10:1,9:30, 5:0 ,4:255,3:0,12:5,7:0}
          {% elif trigger.to_state.state == 'Rain' %}
            {0:8,11:1100}
          {% elif trigger.to_state.state == 'Stepped' %}
            {0:9}
          {% elif trigger.to_state.state == 'Startup' %}
            {0:11,3:1,4:4}
          {% elif trigger.to_state.state == 'Shutdown' %}
            {0:10,3:1}
          {% elif trigger.to_state.state == 'All On' %}
            {0:1}
          {% elif trigger.to_state.state == 'Baby Countdown' %}
            {0:7,10:1,2:[255,147,41],7:0,12:{{ ((274 - states.sensor.baby_countdown.state | int) * 0.4) | int }},4:255,8:1000,4:1}
          {% else %}
            {}
          {% endif %}
        retain: false
    - service: input_select.select_option
      data:
        entity_id: input_select.stairs_mode
        option: 'Select...'