- alias: "Unexpected Boot"
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: template
    value_template: '{{ not is_state("group.adam", "home") }}'
  action:
    - service: notify.ios_adams_iphone
      data:
        message: "Warning: Home Assistant Rebooted."