- alias: "Unexpected Boot"
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: template
    value_template: '{{ not is_state("device_tracker.97097be28e8e4429a0cbe8f813e5d773", "home") }}'
  action:
    - service: notify.ios_adams_iphone
      data:
        message: "Warning: Home Assistant Rebooted."