- alias: door_vibration
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b12379
      movement_type: vibrate
  action:
    - service: notify.ios_adams_iphone
      data:
        message: "Vibration Detected!"