- alias: vibration_test
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b12379
      movement_type: vibrate
  action:
    - service: logbook.log
      data:
        name: Motion Sensor
        message: Vibration

- alias: vibration_test2
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b12379
      movement_type: vibrate
  condition:
    condition: template
    value_template: "{{ (states.automation.vibration_test2.attributes.last_triggered == none) or (as_timestamp(state_attr('automation.vibration_test2', 'last_triggered')) < (as_timestamp(now()) - 300)) }}"
  action:
    - service: notify.email_adam
      data:
        title: "Vibration Detected"
        message: "Vibration Detected"