# Adam Home Queue
- alias: adam_home_queue
  initial_state: true
  trigger:
    platform: state
    entity_id: person.adam
    to: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.queue_home_adam
    
# Lea Home Queue
- alias: lea_home_queue
  initial_state: true
  trigger:
    platform: state
    entity_id: person.leanne
    to: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.queue_home_lea

# Adam Home Queue Timeout
- alias: queue_home_adam_timeout
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.queue_home_adam
    to: 'on'
    for:
      minutes: 10
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.queue_home_adam
    
# Lea Home Queue Timeout
- alias: queue_home_lea_timeout
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.queue_home_lea
    to: 'on'
    for:
      minutes: 10
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.queue_home_lea



    
# Welcome Home Adam
- alias: welcome_home_adam
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'on'
      - condition: state
        entity_id: input_boolean.queue_home_lea
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.welcomeadam
    - service: input_boolean.turn_off
      entity_id: input_boolean.queue_home_adam
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'off' }}"
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.front_room_speaker
        message: "<speak>Welcome Aboard Captain</speak>"

# Welcome Home Leanne
- alias: welcome_home_lea
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'off'
      - condition: state
        entity_id: input_boolean.queue_home_lea
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.welcomelea
    - service: input_boolean.turn_off
      entity_id: input_boolean.queue_home_lea
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'off' }}"
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.front_room_speaker
        message: "<speak>Welcome Home Woman</speak>"
    
# Welcome Home Both
- alias: welcome_home_both
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a5e08d
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.queue_home_adam
        state: 'on'
      - condition: state
        entity_id: input_boolean.queue_home_lea
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.welcomeboth
    - service: input_boolean.turn_off
      entity_id: input_boolean.queue_home_adam
    - service: input_boolean.turn_off
      entity_id: input_boolean.queue_home_lea
    - wait_template: "{{ states.binary_sensor.door_window_sensor_158d0001a5e08d.state == 'off' }}"
    - service: tts.amazon_polly_say
      data:
        entity_id: media_player.front_room_speaker
        message: "<speak>Welcome Home</speak>"      