- platform: mqtt
  name: porch_motion
  state_topic: "shellies/shelly1-227D0A/input/0"
  device_class: motion
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  name: kitchen_switch
  state_topic: "shellies/shelly1-76F1C8/input/0"
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  name: bedroom_blind_availability
  state_topic: "de:66:92:69:03:8c/Connected"
  payload_on: "true"
  payload_off: "false"
